// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: beans.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const completeBean = `-- name: CompleteBean :execrows
UPDATE beans
SET status = 'completed',
    pr_url = ?,
    completed_at = ?,
    updated_at = ?
WHERE id = ?
`

type CompleteBeanParams struct {
	PrUrl       string       `json:"pr_url"`
	CompletedAt sql.NullTime `json:"completed_at"`
	UpdatedAt   time.Time    `json:"updated_at"`
	ID          string       `json:"id"`
}

func (q *Queries) CompleteBean(ctx context.Context, arg CompleteBeanParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, completeBean,
		arg.PrUrl,
		arg.CompletedAt,
		arg.UpdatedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const failBean = `-- name: FailBean :execrows
UPDATE beans
SET status = 'failed',
    error_message = ?,
    completed_at = ?,
    updated_at = ?
WHERE id = ?
`

type FailBeanParams struct {
	ErrorMessage string       `json:"error_message"`
	CompletedAt  sql.NullTime `json:"completed_at"`
	UpdatedAt    time.Time    `json:"updated_at"`
	ID           string       `json:"id"`
}

func (q *Queries) FailBean(ctx context.Context, arg FailBeanParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, failBean,
		arg.ErrorMessage,
		arg.CompletedAt,
		arg.UpdatedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getBean = `-- name: GetBean :one
SELECT id, status, title, pr_url, error_message, zellij_session, zellij_pane,
       worktree_path, started_at, completed_at, created_at, updated_at
FROM beans
WHERE id = ?
`

func (q *Queries) GetBean(ctx context.Context, id string) (Bean, error) {
	row := q.db.QueryRowContext(ctx, getBean, id)
	var i Bean
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.Title,
		&i.PrUrl,
		&i.ErrorMessage,
		&i.ZellijSession,
		&i.ZellijPane,
		&i.WorktreePath,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBeanStatus = `-- name: GetBeanStatus :one
SELECT status
FROM beans
WHERE id = ?
`

func (q *Queries) GetBeanStatus(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRowContext(ctx, getBeanStatus, id)
	var status string
	err := row.Scan(&status)
	return status, err
}

const listBeans = `-- name: ListBeans :many
SELECT id, status, title, pr_url, error_message, zellij_session, zellij_pane,
       worktree_path, started_at, completed_at, created_at, updated_at
FROM beans
ORDER BY created_at DESC
`

func (q *Queries) ListBeans(ctx context.Context) ([]Bean, error) {
	rows, err := q.db.QueryContext(ctx, listBeans)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Bean{}
	for rows.Next() {
		var i Bean
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.Title,
			&i.PrUrl,
			&i.ErrorMessage,
			&i.ZellijSession,
			&i.ZellijPane,
			&i.WorktreePath,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBeansByStatus = `-- name: ListBeansByStatus :many
SELECT id, status, title, pr_url, error_message, zellij_session, zellij_pane,
       worktree_path, started_at, completed_at, created_at, updated_at
FROM beans
WHERE status = ?
ORDER BY created_at DESC
`

func (q *Queries) ListBeansByStatus(ctx context.Context, status string) ([]Bean, error) {
	rows, err := q.db.QueryContext(ctx, listBeansByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Bean{}
	for rows.Next() {
		var i Bean
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.Title,
			&i.PrUrl,
			&i.ErrorMessage,
			&i.ZellijSession,
			&i.ZellijPane,
			&i.WorktreePath,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const startBean = `-- name: StartBean :exec
INSERT INTO beans (id, status, title, zellij_session, zellij_pane, worktree_path, started_at, updated_at)
VALUES (?, 'processing', ?, ?, ?, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET
    status = 'processing',
    title = excluded.title,
    zellij_session = excluded.zellij_session,
    zellij_pane = excluded.zellij_pane,
    worktree_path = excluded.worktree_path,
    started_at = excluded.started_at,
    updated_at = excluded.updated_at
`

type StartBeanParams struct {
	ID            string       `json:"id"`
	Title         string       `json:"title"`
	ZellijSession string       `json:"zellij_session"`
	ZellijPane    string       `json:"zellij_pane"`
	WorktreePath  string       `json:"worktree_path"`
	StartedAt     sql.NullTime `json:"started_at"`
	UpdatedAt     time.Time    `json:"updated_at"`
}

func (q *Queries) StartBean(ctx context.Context, arg StartBeanParams) error {
	_, err := q.db.ExecContext(ctx, startBean,
		arg.ID,
		arg.Title,
		arg.ZellijSession,
		arg.ZellijPane,
		arg.WorktreePath,
		arg.StartedAt,
		arg.UpdatedAt,
	)
	return err
}
