// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: complexity.sql

package sqlc

import (
	"context"
	"strings"
)

const cacheComplexity = `-- name: CacheComplexity :exec
REPLACE INTO complexity_cache (bean_id, description_hash, complexity_score, estimated_tokens)
VALUES (?, ?, ?, ?)
`

type CacheComplexityParams struct {
	BeanID          string `json:"bean_id"`
	DescriptionHash string `json:"description_hash"`
	ComplexityScore int64  `json:"complexity_score"`
	EstimatedTokens int64  `json:"estimated_tokens"`
}

func (q *Queries) CacheComplexity(ctx context.Context, arg CacheComplexityParams) error {
	_, err := q.db.ExecContext(ctx, cacheComplexity,
		arg.BeanID,
		arg.DescriptionHash,
		arg.ComplexityScore,
		arg.EstimatedTokens,
	)
	return err
}

const countEstimatedBeans = `-- name: CountEstimatedBeans :one
SELECT COUNT(DISTINCT bean_id) as count
FROM complexity_cache
WHERE bean_id IN (/*SLICE:bean_ids*/?)
`

func (q *Queries) CountEstimatedBeans(ctx context.Context, beanIds []string) (int64, error) {
	query := countEstimatedBeans
	var queryParams []interface{}
	if len(beanIds) > 0 {
		for _, v := range beanIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:bean_ids*/?", strings.Repeat(",?", len(beanIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:bean_ids*/?", "NULL", 1)
	}
	row := q.db.QueryRowContext(ctx, query, queryParams...)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getAllCachedComplexity = `-- name: GetAllCachedComplexity :many
SELECT bean_id, complexity_score, estimated_tokens
FROM complexity_cache
`

type GetAllCachedComplexityRow struct {
	BeanID          string `json:"bean_id"`
	ComplexityScore int64  `json:"complexity_score"`
	EstimatedTokens int64  `json:"estimated_tokens"`
}

func (q *Queries) GetAllCachedComplexity(ctx context.Context) ([]GetAllCachedComplexityRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllCachedComplexity)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAllCachedComplexityRow{}
	for rows.Next() {
		var i GetAllCachedComplexityRow
		if err := rows.Scan(&i.BeanID, &i.ComplexityScore, &i.EstimatedTokens); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCachedComplexity = `-- name: GetCachedComplexity :one
SELECT complexity_score, estimated_tokens
FROM complexity_cache
WHERE bean_id = ? AND description_hash = ?
`

type GetCachedComplexityParams struct {
	BeanID          string `json:"bean_id"`
	DescriptionHash string `json:"description_hash"`
}

type GetCachedComplexityRow struct {
	ComplexityScore int64 `json:"complexity_score"`
	EstimatedTokens int64 `json:"estimated_tokens"`
}

func (q *Queries) GetCachedComplexity(ctx context.Context, arg GetCachedComplexityParams) (GetCachedComplexityRow, error) {
	row := q.db.QueryRowContext(ctx, getCachedComplexity, arg.BeanID, arg.DescriptionHash)
	var i GetCachedComplexityRow
	err := row.Scan(&i.ComplexityScore, &i.EstimatedTokens)
	return i, err
}
