// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: messages.sql

package sqlc

import (
	"context"
	"database/sql"
)

const deleteMessage = `-- name: DeleteMessage :execresult
DELETE FROM messages WHERE id = ?
`

func (q *Queries) DeleteMessage(ctx context.Context, id int64) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteMessage, id)
}

const insertMessage = `-- name: InsertMessage :execresult
INSERT INTO messages (source, text, work_id, task_id, bead_id, event_type)
VALUES (?, ?, ?, ?, ?, ?)
`

type InsertMessageParams struct {
	Source    string         `json:"source"`
	Text      string         `json:"text"`
	WorkID    sql.NullString `json:"work_id"`
	TaskID    sql.NullString `json:"task_id"`
	BeadID    sql.NullString `json:"bead_id"`
	EventType sql.NullString `json:"event_type"`
}

func (q *Queries) InsertMessage(ctx context.Context, arg InsertMessageParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertMessage,
		arg.Source,
		arg.Text,
		arg.WorkID,
		arg.TaskID,
		arg.BeadID,
		arg.EventType,
	)
}

const listMessages = `-- name: ListMessages :many
SELECT id, source, text, work_id, task_id, bead_id, event_type, created_at
FROM messages ORDER BY created_at ASC LIMIT ?
`

func (q *Queries) ListMessages(ctx context.Context, limit int64) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, listMessages, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.Source,
			&i.Text,
			&i.WorkID,
			&i.TaskID,
			&i.BeadID,
			&i.EventType,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentMessages = `-- name: ListRecentMessages :many
SELECT id, source, text, work_id, task_id, bead_id, event_type, created_at
FROM messages ORDER BY created_at DESC LIMIT ?
`

func (q *Queries) ListRecentMessages(ctx context.Context, limit int64) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, listRecentMessages, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.Source,
			&i.Text,
			&i.WorkID,
			&i.TaskID,
			&i.BeadID,
			&i.EventType,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
