// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
	"time"
)

type Bean struct {
	ID           string       `json:"id"`
	Status       string       `json:"status"`
	Title        string       `json:"title"`
	PrUrl        string       `json:"pr_url"`
	ErrorMessage string       `json:"error_message"`
	WorktreePath string       `json:"worktree_path"`
	StartedAt    sql.NullTime `json:"started_at"`
	CompletedAt  sql.NullTime `json:"completed_at"`
	CreatedAt    time.Time    `json:"created_at"`
	UpdatedAt    time.Time    `json:"updated_at"`
}

type ComplexityCache struct {
	BeanID          string    `json:"bean_id"`
	DescriptionHash string    `json:"description_hash"`
	ComplexityScore int64     `json:"complexity_score"`
	EstimatedTokens int64     `json:"estimated_tokens"`
	CreatedAt       time.Time `json:"created_at"`
}

type PlanSession struct {
	BeanID      string    `json:"bean_id"`
	SessionName string    `json:"session_name"`
	TabName     string    `json:"tab_name"`
	Pid         int64     `json:"pid"`
	StartedAt   time.Time `json:"started_at"`
}

type PrFeedback struct {
	ID           string         `json:"id"`
	WorkID       string         `json:"work_id"`
	PrUrl        string         `json:"pr_url"`
	FeedbackType string         `json:"feedback_type"`
	Title        string         `json:"title"`
	Description  string         `json:"description"`
	SourceUrl    sql.NullString `json:"source_url"`
	SourceID     sql.NullString `json:"source_id"`
	SourceType   sql.NullString `json:"source_type"`
	SourceName   sql.NullString `json:"source_name"`
	Context      sql.NullString `json:"context"`
	Priority     int64          `json:"priority"`
	BeanID       sql.NullString `json:"bean_id"`
	CreatedAt    time.Time      `json:"created_at"`
	ProcessedAt  sql.NullTime   `json:"processed_at"`
	ResolvedAt   sql.NullTime   `json:"resolved_at"`
}

type Process struct {
	ID          string         `json:"id"`
	ProcessType string         `json:"process_type"`
	WorkID      sql.NullString `json:"work_id"`
	Pid         int64          `json:"pid"`
	Hostname    string         `json:"hostname"`
	Heartbeat   time.Time      `json:"heartbeat"`
	StartedAt   time.Time      `json:"started_at"`
	PprofPort   sql.NullInt64  `json:"pprof_port"`
}

type Scheduler struct {
	ID             string         `json:"id"`
	WorkID         string         `json:"work_id"`
	TaskType       string         `json:"task_type"`
	ScheduledAt    time.Time      `json:"scheduled_at"`
	ExecutedAt     sql.NullTime   `json:"executed_at"`
	Status         string         `json:"status"`
	ErrorMessage   sql.NullString `json:"error_message"`
	Metadata       string         `json:"metadata"`
	AttemptCount   int64          `json:"attempt_count"`
	MaxAttempts    int64          `json:"max_attempts"`
	IdempotencyKey sql.NullString `json:"idempotency_key"`
	CreatedAt      time.Time      `json:"created_at"`
	UpdatedAt      time.Time      `json:"updated_at"`
}

type SchemaMigration struct {
	Version   string       `json:"version"`
	AppliedAt sql.NullTime `json:"applied_at"`
	Name      string       `json:"name"`
	DownSql   string       `json:"down_sql"`
}

type Task struct {
	ID               string       `json:"id"`
	Status           string       `json:"status"`
	TaskType         string       `json:"task_type"`
	ComplexityBudget int64        `json:"complexity_budget"`
	ActualComplexity int64        `json:"actual_complexity"`
	WorkID           string       `json:"work_id"`
	WorktreePath     string       `json:"worktree_path"`
	PrUrl            string       `json:"pr_url"`
	ErrorMessage     string       `json:"error_message"`
	StartedAt        sql.NullTime `json:"started_at"`
	CompletedAt      sql.NullTime `json:"completed_at"`
	CreatedAt        time.Time    `json:"created_at"`
	SpawnedAt        sql.NullTime `json:"spawned_at"`
	SpawnStatus      string       `json:"spawn_status"`
	LastActivity     sql.NullTime `json:"last_activity"`
	TaskNumber       int64        `json:"task_number"`
}

type TaskBean struct {
	TaskID string `json:"task_id"`
	BeanID string `json:"bean_id"`
	Status string `json:"status"`
}

type TaskDependency struct {
	TaskID          string    `json:"task_id"`
	DependsOnTaskID string    `json:"depends_on_task_id"`
	CreatedAt       time.Time `json:"created_at"`
}

type TaskMetadatum struct {
	TaskID    string    `json:"task_id"`
	Key       string    `json:"key"`
	Value     string    `json:"value"`
	CreatedAt time.Time `json:"created_at"`
}

type Work struct {
	ID                 string       `json:"id"`
	Status             string       `json:"status"`
	Name               string       `json:"name"`
	WorktreePath       string       `json:"worktree_path"`
	BranchName         string       `json:"branch_name"`
	BaseBranch         string       `json:"base_branch"`
	RootIssueID        string       `json:"root_issue_id"`
	PrUrl              string       `json:"pr_url"`
	ErrorMessage       string       `json:"error_message"`
	StartedAt          sql.NullTime `json:"started_at"`
	CompletedAt        sql.NullTime `json:"completed_at"`
	CreatedAt          time.Time    `json:"created_at"`
	Auto               bool         `json:"auto"`
	CiStatus           string       `json:"ci_status"`
	ApprovalStatus     string       `json:"approval_status"`
	Approvers          string       `json:"approvers"`
	LastPrPollAt       sql.NullTime `json:"last_pr_poll_at"`
	HasUnseenPrChanges bool         `json:"has_unseen_pr_changes"`
	PrState            string       `json:"pr_state"`
	MergeableState     string       `json:"mergeable_state"`
}

type WorkBean struct {
	WorkID    string    `json:"work_id"`
	BeanID    string    `json:"bean_id"`
	Position  int64     `json:"position"`
	CreatedAt time.Time `json:"created_at"`
}

type WorkTask struct {
	WorkID   string `json:"work_id"`
	TaskID   string `json:"task_id"`
	Position int64  `json:"position"`
}

type WorkTaskCounter struct {
	WorkID      string `json:"work_id"`
	NextTaskNum int64  `json:"next_task_num"`
}
