// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

type Querier interface {
	AddTaskDependency(ctx context.Context, arg AddTaskDependencyParams) error
	AddTaskToWork(ctx context.Context, arg AddTaskToWorkParams) error
	AddWorkBean(ctx context.Context, arg AddWorkBeanParams) error
	AddWorkBeansBatch(ctx context.Context, arg AddWorkBeansBatchParams) error
	CacheComplexity(ctx context.Context, arg CacheComplexityParams) error
	CompleteBean(ctx context.Context, arg CompleteBeanParams) (int64, error)
	CompleteTask(ctx context.Context, arg CompleteTaskParams) (int64, error)
	CompleteTaskBean(ctx context.Context, arg CompleteTaskBeanParams) (int64, error)
	CompleteWork(ctx context.Context, arg CompleteWorkParams) (int64, error)
	CountEstimatedBeans(ctx context.Context, beanIds []string) (int64, error)
	CountPendingTasksForWork(ctx context.Context, workID string) (int64, error)
	CountTaskBeanStatuses(ctx context.Context, taskID string) (CountTaskBeanStatusesRow, error)
	// Count PR feedback items that have beans which are not yet assigned to any task and not resolved/closed.
	CountUnassignedFeedbackForWork(ctx context.Context, workID string) (int64, error)
	CreateMigrationsTable(ctx context.Context) error
	CreatePRFeedback(ctx context.Context, arg CreatePRFeedbackParams) error
	CreateScheduledTask(ctx context.Context, arg CreateScheduledTaskParams) error
	CreateScheduledTaskWithRetry(ctx context.Context, arg CreateScheduledTaskWithRetryParams) error
	CreateTask(ctx context.Context, arg CreateTaskParams) error
	CreateTaskBean(ctx context.Context, arg CreateTaskBeanParams) error
	CreateWork(ctx context.Context, arg CreateWorkParams) error
	DeleteCompletedTasksOlderThan(ctx context.Context, executedAt sql.NullTime) error
	DeleteControlPlaneProcess(ctx context.Context) error
	DeleteMigration(ctx context.Context, version string) error
	DeleteOrchestratorByWorkID(ctx context.Context, workID sql.NullString) error
	DeletePRFeedback(ctx context.Context, id string) error
	DeletePRFeedbackForWork(ctx context.Context, workID string) error
	DeleteProcess(ctx context.Context, id string) error
	DeleteScheduledTask(ctx context.Context, id string) error
	DeleteSchedulerForWork(ctx context.Context, workID string) (int64, error)
	DeleteStaleProcesses(ctx context.Context, dollar_1 sql.NullString) error
	DeleteTask(ctx context.Context, id string) (int64, error)
	DeleteTaskBeansByTask(ctx context.Context, taskID string) (int64, error)
	DeleteTaskBeansForWork(ctx context.Context, workID string) (int64, error)
	DeleteTaskDependencies(ctx context.Context, taskID string) (int64, error)
	DeleteTaskDependenciesForWork(ctx context.Context, workID string) (int64, error)
	DeleteTaskDependency(ctx context.Context, arg DeleteTaskDependencyParams) (int64, error)
	DeleteTaskMetadata(ctx context.Context, arg DeleteTaskMetadataParams) (int64, error)
	DeleteTasksForWork(ctx context.Context, workID string) (int64, error)
	DeleteWork(ctx context.Context, id string) (int64, error)
	DeleteWorkBeans(ctx context.Context, workID string) (int64, error)
	DeleteWorkTaskByTask(ctx context.Context, taskID string) (int64, error)
	DeleteWorkTasks(ctx context.Context, workID string) (int64, error)
	FailBean(ctx context.Context, arg FailBeanParams) (int64, error)
	FailTask(ctx context.Context, arg FailTaskParams) (int64, error)
	FailTaskBean(ctx context.Context, arg FailTaskBeanParams) (int64, error)
	FailWork(ctx context.Context, arg FailWorkParams) (int64, error)
	// Returns all beans assigned to any work, with their work ID.
	// This is used by plan mode to show which beans are already assigned.
	GetAllAssignedBeans(ctx context.Context) ([]GetAllAssignedBeansRow, error)
	GetAllCachedComplexity(ctx context.Context) ([]GetAllCachedComplexityRow, error)
	GetAllProcesses(ctx context.Context) ([]Process, error)
	GetAllTaskMetadata(ctx context.Context, taskID string) ([]GetAllTaskMetadataRow, error)
	GetAndIncrementTaskCounter(ctx context.Context, workID string) (int64, error)
	GetAppliedMigrations(ctx context.Context) ([]string, error)
	GetBean(ctx context.Context, id string) (Bean, error)
	GetBeanStatus(ctx context.Context, id string) (string, error)
	GetCachedComplexity(ctx context.Context, arg GetCachedComplexityParams) (GetCachedComplexityRow, error)
	GetControlPlaneProcess(ctx context.Context) (Process, error)
	GetLastMigration(ctx context.Context) (string, error)
	GetLastWorkID(ctx context.Context) (string, error)
	GetMaxWorkBeanPosition(ctx context.Context, workID string) (int64, error)
	GetMigrationDownSQL(ctx context.Context, version string) (GetMigrationDownSQLRow, error)
	GetNextScheduledTask(ctx context.Context) (Scheduler, error)
	GetOrchestratorProcess(ctx context.Context, workID sql.NullString) (Process, error)
	GetOverdueTasks(ctx context.Context) ([]Scheduler, error)
	GetPRFeedback(ctx context.Context, id string) (PrFeedback, error)
	GetPRFeedbackByBean(ctx context.Context, beanID sql.NullString) (PrFeedback, error)
	GetPRFeedbackBySourceID(ctx context.Context, arg GetPRFeedbackBySourceIDParams) (PrFeedback, error)
	GetPRTaskForWork(ctx context.Context, workID string) (GetPRTaskForWorkRow, error)
	GetPendingTaskByType(ctx context.Context, arg GetPendingTaskByTypeParams) (Scheduler, error)
	GetProcess(ctx context.Context, id string) (Process, error)
	GetProcessByWorkID(ctx context.Context, workID sql.NullString) (Process, error)
	GetReadyTasksForWork(ctx context.Context, workID string) ([]GetReadyTasksForWorkRow, error)
	GetScheduledTaskByID(ctx context.Context, id string) (Scheduler, error)
	GetScheduledTasksForWork(ctx context.Context, workID string) ([]Scheduler, error)
	GetStaleProcesses(ctx context.Context, dollar_1 sql.NullString) ([]Process, error)
	GetTask(ctx context.Context, id string) (GetTaskRow, error)
	GetTaskBeanStatus(ctx context.Context, arg GetTaskBeanStatusParams) (string, error)
	GetTaskBeans(ctx context.Context, taskID string) ([]string, error)
	GetTaskBeansForWork(ctx context.Context, workID string) ([]TaskBean, error)
	GetTaskBeansWithStatus(ctx context.Context, taskID string) ([]TaskBean, error)
	GetTaskByIdempotencyKey(ctx context.Context, idempotencyKey sql.NullString) (Scheduler, error)
	GetTaskDependencies(ctx context.Context, taskID string) ([]string, error)
	GetTaskDependents(ctx context.Context, dependsOnTaskID string) ([]string, error)
	GetTaskForBean(ctx context.Context, beanID string) (string, error)
	GetTaskMetadata(ctx context.Context, arg GetTaskMetadataParams) (string, error)
	GetTasksWithActivity(ctx context.Context) ([]GetTasksWithActivityRow, error)
	// Get bean IDs from PR feedback items that are not yet assigned to any task and not resolved/closed.
	GetUnassignedFeedbackBeanIDs(ctx context.Context, workID string) ([]sql.NullString, error)
	GetUnassignedWorkBeans(ctx context.Context, workID string) ([]WorkBean, error)
	GetUnresolvedFeedbackForBeans(ctx context.Context, beanIds []sql.NullString) ([]PrFeedback, error)
	GetUnresolvedFeedbackForWork(ctx context.Context, workID string) ([]PrFeedback, error)
	GetWork(ctx context.Context, id string) (Work, error)
	GetWorkBeans(ctx context.Context, workID string) ([]WorkBean, error)
	GetWorkByDirectory(ctx context.Context, worktreePath string) (Work, error)
	GetWorkTasks(ctx context.Context, workID string) ([]GetWorkTasksRow, error)
	GetWorksWithPRs(ctx context.Context) ([]Work, error)
	GetWorksWithUnseenChanges(ctx context.Context) ([]Work, error)
	HasExistingFeedback(ctx context.Context, arg HasExistingFeedbackParams) (int64, error)
	// Only consider feedback "existing" if a bean was actually created.
	// This allows retry if bean creation failed on a previous attempt.
	HasExistingFeedbackBySourceID(ctx context.Context, arg HasExistingFeedbackBySourceIDParams) (int64, error)
	HasPendingDependencies(ctx context.Context, taskID string) (bool, error)
	IdleWork(ctx context.Context, id string) (int64, error)
	IdleWorkWithPR(ctx context.Context, arg IdleWorkWithPRParams) (int64, error)
	IncrementAttemptAndReschedule(ctx context.Context, arg IncrementAttemptAndRescheduleParams) error
	InitializeTaskCounter(ctx context.Context, workID string) error
	IsBeanInTask(ctx context.Context, arg IsBeanInTaskParams) (bool, error)
	IsControlPlaneAlive(ctx context.Context, dollar_1 sql.NullString) (int64, error)
	IsOrchestratorAlive(ctx context.Context, arg IsOrchestratorAliveParams) (int64, error)
	ListBeans(ctx context.Context) ([]Bean, error)
	ListBeansByStatus(ctx context.Context, status string) ([]Bean, error)
	ListMigrationVersions(ctx context.Context) ([]string, error)
	ListMigrationsWithDetails(ctx context.Context) ([]ListMigrationsWithDetailsRow, error)
	ListPRFeedback(ctx context.Context, workID string) ([]PrFeedback, error)
	ListTasks(ctx context.Context) ([]ListTasksRow, error)
	ListTasksByStatus(ctx context.Context, status string) ([]ListTasksByStatusRow, error)
	ListUnprocessedPRFeedback(ctx context.Context, workID string) ([]PrFeedback, error)
	ListWorks(ctx context.Context) ([]Work, error)
	ListWorksByStatus(ctx context.Context, status string) ([]Work, error)
	MarkPRFeedbackProcessed(ctx context.Context, arg MarkPRFeedbackProcessedParams) error
	MarkPRFeedbackResolved(ctx context.Context, id string) error
	MarkTaskCompleted(ctx context.Context, id string) error
	MarkTaskCompletedByIdempotencyKey(ctx context.Context, idempotencyKey sql.NullString) error
	MarkTaskExecuting(ctx context.Context, id string) error
	MarkTaskFailed(ctx context.Context, arg MarkTaskFailedParams) error
	MarkWorkPRSeen(ctx context.Context, id string) (int64, error)
	MergeWork(ctx context.Context, arg MergeWorkParams) (int64, error)
	RecordMigration(ctx context.Context, version string) error
	RecordMigrationWithDown(ctx context.Context, arg RecordMigrationWithDownParams) error
	RegisterProcess(ctx context.Context, arg RegisterProcessParams) error
	RemoveWorkBean(ctx context.Context, arg RemoveWorkBeanParams) (int64, error)
	RescheduleTask(ctx context.Context, arg RescheduleTaskParams) error
	// Reset any tasks stuck in 'executing' status back to 'pending'.
	// Used when the control plane starts up to recover from a crash.
	ResetExecutingTasksToPending(ctx context.Context) (int64, error)
	ResetTaskBeanStatus(ctx context.Context, arg ResetTaskBeanStatusParams) (int64, error)
	ResetTaskBeanStatuses(ctx context.Context, taskID string) (int64, error)
	ResetTaskStatus(ctx context.Context, id string) (int64, error)
	RestartWork(ctx context.Context, id string) (int64, error)
	ResumeWork(ctx context.Context, id string) (int64, error)
	SetTaskMetadata(ctx context.Context, arg SetTaskMetadataParams) error
	SetWorkHasUnseenPRChanges(ctx context.Context, arg SetWorkHasUnseenPRChangesParams) (int64, error)
	SetWorkPRURL(ctx context.Context, arg SetWorkPRURLParams) (int64, error)
	SpawnTask(ctx context.Context, arg SpawnTaskParams) (int64, error)
	StartBean(ctx context.Context, arg StartBeanParams) error
	StartTask(ctx context.Context, arg StartTaskParams) (int64, error)
	StartWork(ctx context.Context, arg StartWorkParams) (int64, error)
	UpdateHeartbeat(ctx context.Context, id string) (sql.Result, error)
	UpdateHeartbeatWithTime(ctx context.Context, arg UpdateHeartbeatWithTimeParams) (sql.Result, error)
	UpdateMigrationDownSQL(ctx context.Context, arg UpdateMigrationDownSQLParams) error
	UpdatePprofPort(ctx context.Context, arg UpdatePprofPortParams) error
	UpdateScheduledTaskTime(ctx context.Context, arg UpdateScheduledTaskTimeParams) error
	UpdateTaskActivity(ctx context.Context, arg UpdateTaskActivityParams) (int64, error)
	UpdateWorkPRStatus(ctx context.Context, arg UpdateWorkPRStatusParams) (int64, error)
	UpdateWorkWorktreePath(ctx context.Context, arg UpdateWorkWorktreePathParams) (int64, error)
	WatchSchedulerChanges(ctx context.Context, updatedAt time.Time) ([]Scheduler, error)
}

var _ Querier = (*Queries)(nil)
