// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: task_metadata.sql

package sqlc

import (
	"context"
)

const deleteTaskMetadata = `-- name: DeleteTaskMetadata :execrows
DELETE FROM task_metadata WHERE task_id = ? AND key = ?
`

type DeleteTaskMetadataParams struct {
	TaskID string `json:"task_id"`
	Key    string `json:"key"`
}

func (q *Queries) DeleteTaskMetadata(ctx context.Context, arg DeleteTaskMetadataParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteTaskMetadata, arg.TaskID, arg.Key)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getAllTaskMetadata = `-- name: GetAllTaskMetadata :many
SELECT key, value FROM task_metadata WHERE task_id = ?
`

type GetAllTaskMetadataRow struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

func (q *Queries) GetAllTaskMetadata(ctx context.Context, taskID string) ([]GetAllTaskMetadataRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllTaskMetadata, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAllTaskMetadataRow{}
	for rows.Next() {
		var i GetAllTaskMetadataRow
		if err := rows.Scan(&i.Key, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTaskMetadata = `-- name: GetTaskMetadata :one
SELECT value FROM task_metadata WHERE task_id = ? AND key = ?
`

type GetTaskMetadataParams struct {
	TaskID string `json:"task_id"`
	Key    string `json:"key"`
}

func (q *Queries) GetTaskMetadata(ctx context.Context, arg GetTaskMetadataParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getTaskMetadata, arg.TaskID, arg.Key)
	var value string
	err := row.Scan(&value)
	return value, err
}

const setTaskMetadata = `-- name: SetTaskMetadata :exec
INSERT INTO task_metadata (task_id, key, value)
VALUES (?, ?, ?)
ON CONFLICT (task_id, key) DO UPDATE SET value = excluded.value
`

type SetTaskMetadataParams struct {
	TaskID string `json:"task_id"`
	Key    string `json:"key"`
	Value  string `json:"value"`
}

func (q *Queries) SetTaskMetadata(ctx context.Context, arg SetTaskMetadataParams) error {
	_, err := q.db.ExecContext(ctx, setTaskMetadata, arg.TaskID, arg.Key, arg.Value)
	return err
}
