// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: work_beans.sql

package sqlc

import (
	"context"
)

const addWorkBean = `-- name: AddWorkBean :exec
INSERT INTO work_beans (work_id, bean_id, position)
VALUES (?, ?, ?)
`

type AddWorkBeanParams struct {
	WorkID   string `json:"work_id"`
	BeanID   string `json:"bean_id"`
	Position int64  `json:"position"`
}

func (q *Queries) AddWorkBean(ctx context.Context, arg AddWorkBeanParams) error {
	_, err := q.db.ExecContext(ctx, addWorkBean, arg.WorkID, arg.BeanID, arg.Position)
	return err
}

const addWorkBeansBatch = `-- name: AddWorkBeansBatch :exec
INSERT INTO work_beans (work_id, bean_id, position)
VALUES (?, ?, ?)
ON CONFLICT (work_id, bean_id) DO UPDATE SET
    position = excluded.position
`

type AddWorkBeansBatchParams struct {
	WorkID   string `json:"work_id"`
	BeanID   string `json:"bean_id"`
	Position int64  `json:"position"`
}

func (q *Queries) AddWorkBeansBatch(ctx context.Context, arg AddWorkBeansBatchParams) error {
	_, err := q.db.ExecContext(ctx, addWorkBeansBatch, arg.WorkID, arg.BeanID, arg.Position)
	return err
}

const deleteWorkBeans = `-- name: DeleteWorkBeans :execrows
DELETE FROM work_beans
WHERE work_id = ?
`

func (q *Queries) DeleteWorkBeans(ctx context.Context, workID string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteWorkBeans, workID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getAllAssignedBeans = `-- name: GetAllAssignedBeans :many
SELECT bean_id, work_id
FROM work_beans
ORDER BY bean_id
`

type GetAllAssignedBeansRow struct {
	BeanID string `json:"bean_id"`
	WorkID string `json:"work_id"`
}

// Returns all beans assigned to any work, with their work ID.
// This is used by plan mode to show which beans are already assigned.
func (q *Queries) GetAllAssignedBeans(ctx context.Context) ([]GetAllAssignedBeansRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllAssignedBeans)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAllAssignedBeansRow{}
	for rows.Next() {
		var i GetAllAssignedBeansRow
		if err := rows.Scan(&i.BeanID, &i.WorkID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMaxWorkBeanPosition = `-- name: GetMaxWorkBeanPosition :one
SELECT CAST(COALESCE(MAX(position), -1) AS INTEGER) as max_position
FROM work_beans
WHERE work_id = ?
`

func (q *Queries) GetMaxWorkBeanPosition(ctx context.Context, workID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getMaxWorkBeanPosition, workID)
	var max_position int64
	err := row.Scan(&max_position)
	return max_position, err
}

const getUnassignedWorkBeans = `-- name: GetUnassignedWorkBeans :many
SELECT wb.work_id, wb.bean_id, wb.position, wb.created_at
FROM work_beans wb
WHERE wb.work_id = ?
  AND NOT EXISTS (
    SELECT 1 FROM task_beans tb
    JOIN work_tasks wt ON tb.task_id = wt.task_id
    WHERE wt.work_id = wb.work_id AND tb.bean_id = wb.bean_id
  )
ORDER BY wb.position
`

func (q *Queries) GetUnassignedWorkBeans(ctx context.Context, workID string) ([]WorkBean, error) {
	rows, err := q.db.QueryContext(ctx, getUnassignedWorkBeans, workID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkBean{}
	for rows.Next() {
		var i WorkBean
		if err := rows.Scan(
			&i.WorkID,
			&i.BeanID,
			&i.Position,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWorkBeans = `-- name: GetWorkBeans :many
SELECT work_id, bean_id, position, created_at
FROM work_beans
WHERE work_id = ?
ORDER BY position
`

func (q *Queries) GetWorkBeans(ctx context.Context, workID string) ([]WorkBean, error) {
	rows, err := q.db.QueryContext(ctx, getWorkBeans, workID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkBean{}
	for rows.Next() {
		var i WorkBean
		if err := rows.Scan(
			&i.WorkID,
			&i.BeanID,
			&i.Position,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isBeanInTask = `-- name: IsBeanInTask :one
SELECT COUNT(*) > 0 as in_task
FROM task_beans tb
JOIN work_tasks wt ON tb.task_id = wt.task_id
WHERE wt.work_id = ? AND tb.bean_id = ?
`

type IsBeanInTaskParams struct {
	WorkID string `json:"work_id"`
	BeanID string `json:"bean_id"`
}

func (q *Queries) IsBeanInTask(ctx context.Context, arg IsBeanInTaskParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, isBeanInTask, arg.WorkID, arg.BeanID)
	var in_task bool
	err := row.Scan(&in_task)
	return in_task, err
}

const removeWorkBean = `-- name: RemoveWorkBean :execrows
DELETE FROM work_beans
WHERE work_id = ? AND bean_id = ?
`

type RemoveWorkBeanParams struct {
	WorkID string `json:"work_id"`
	BeanID string `json:"bean_id"`
}

func (q *Queries) RemoveWorkBean(ctx context.Context, arg RemoveWorkBeanParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, removeWorkBean, arg.WorkID, arg.BeanID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
