// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package control_test

import (
	"context"
	"github.com/sargehq/sarge/internal/control"
	"io"
	"sync"
)

// Ensure, that WorkDestroyerMock does implement control.WorkDestroyer.
// If this is not the case, regenerate this file with moq.
var _ control.WorkDestroyer = &WorkDestroyerMock{}

// WorkDestroyerMock is a mock implementation of control.WorkDestroyer.
//
//	func TestSomethingThatUsesWorkDestroyer(t *testing.T) {
//
//		// make and configure a mocked control.WorkDestroyer
//		mockedWorkDestroyer := &WorkDestroyerMock{
//			DestroyWorkFunc: func(ctx context.Context, workID string, w io.Writer) error {
//				panic("mock out the DestroyWork method")
//			},
//		}
//
//		// use mockedWorkDestroyer in code that requires control.WorkDestroyer
//		// and then make assertions.
//
//	}
type WorkDestroyerMock struct {
	// DestroyWorkFunc mocks the DestroyWork method.
	DestroyWorkFunc func(ctx context.Context, workID string, w io.Writer) error

	// calls tracks calls to the methods.
	calls struct {
		// DestroyWork holds details about calls to the DestroyWork method.
		DestroyWork []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// WorkID is the workID argument value.
			WorkID string
			// W is the w argument value.
			W io.Writer
		}
	}
	lockDestroyWork sync.RWMutex
}

// DestroyWork calls DestroyWorkFunc.
func (mock *WorkDestroyerMock) DestroyWork(ctx context.Context, workID string, w io.Writer) error {
	callInfo := struct {
		Ctx    context.Context
		WorkID string
		W      io.Writer
	}{
		Ctx:    ctx,
		WorkID: workID,
		W:      w,
	}
	mock.lockDestroyWork.Lock()
	mock.calls.DestroyWork = append(mock.calls.DestroyWork, callInfo)
	mock.lockDestroyWork.Unlock()
	if mock.DestroyWorkFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.DestroyWorkFunc(ctx, workID, w)
}

// DestroyWorkCalls gets all the calls that were made to DestroyWork.
// Check the length with:
//
//	len(mockedWorkDestroyer.DestroyWorkCalls())
func (mock *WorkDestroyerMock) DestroyWorkCalls() []struct {
	Ctx    context.Context
	WorkID string
	W      io.Writer
} {
	var calls []struct {
		Ctx    context.Context
		WorkID string
		W      io.Writer
	}
	mock.lockDestroyWork.RLock()
	calls = mock.calls.DestroyWork
	mock.lockDestroyWork.RUnlock()
	return calls
}
