// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package beans

import (
	"context"
	"sync"
)

// Ensure, that BeansCLIMock does implement CLI.
// If this is not the case, regenerate this file with moq.
var _ CLI = &BeansCLIMock{}

// BeansCLIMock is a mock implementation of CLI.
//
//	func TestSomethingThatUsesCLI(t *testing.T) {
//
//		// make and configure a mocked CLI
//		mockedCLI := &BeansCLIMock{
//			AddCommentFunc: func(ctx context.Context, beanID string, comment string) error {
//				panic("mock out the AddComment method")
//			},
//			AddDependencyFunc: func(ctx context.Context, beanID string, dependsOnID string) error {
//				panic("mock out the AddDependency method")
//			},
//			AddTagsFunc: func(ctx context.Context, beanID string, tags []string) error {
//				panic("mock out the AddTags method")
//			},
//			CloseFunc: func(ctx context.Context, beanID string) error {
//				panic("mock out the Close method")
//			},
//			CreateFunc: func(ctx context.Context, opts CreateOptions) (string, error) {
//				panic("mock out the Create method")
//			},
//			DeleteFunc: func(ctx context.Context, beanID string, force bool) error {
//				panic("mock out the Delete method")
//			},
//			ReopenFunc: func(ctx context.Context, beanID string) error {
//				panic("mock out the Reopen method")
//			},
//			UpdateFunc: func(ctx context.Context, beanID string, opts UpdateOptions) error {
//				panic("mock out the Update method")
//			},
//		}
//
//		// use mockedCLI in code that requires CLI
//		// and then make assertions.
//
//	}
type BeansCLIMock struct {
	// AddCommentFunc mocks the AddComment method.
	AddCommentFunc func(ctx context.Context, beanID string, comment string) error

	// AddDependencyFunc mocks the AddDependency method.
	AddDependencyFunc func(ctx context.Context, beanID string, dependsOnID string) error

	// AddTagsFunc mocks the AddTags method.
	AddTagsFunc func(ctx context.Context, beanID string, tags []string) error

	// CloseFunc mocks the Close method.
	CloseFunc func(ctx context.Context, beanID string) error

	// CreateFunc mocks the Create method.
	CreateFunc func(ctx context.Context, opts CreateOptions) (string, error)

	// DeleteFunc mocks the Delete method.
	DeleteFunc func(ctx context.Context, beanID string, force bool) error

	// ReopenFunc mocks the Reopen method.
	ReopenFunc func(ctx context.Context, beanID string) error

	// UpdateFunc mocks the Update method.
	UpdateFunc func(ctx context.Context, beanID string, opts UpdateOptions) error

	// calls tracks calls to the methods.
	calls struct {
		// AddComment holds details about calls to the AddComment method.
		AddComment []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// BeanID is the beanID argument value.
			BeanID string
			// Comment is the comment argument value.
			Comment string
		}
		// AddDependency holds details about calls to the AddDependency method.
		AddDependency []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// BeanID is the beanID argument value.
			BeanID string
			// DependsOnID is the dependsOnID argument value.
			DependsOnID string
		}
		// AddTags holds details about calls to the AddTags method.
		AddTags []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// BeanID is the beanID argument value.
			BeanID string
			// Tags is the tags argument value.
			Tags []string
		}
		// Close holds details about calls to the Close method.
		Close []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// BeanID is the beanID argument value.
			BeanID string
		}
		// Create holds details about calls to the Create method.
		Create []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Opts is the opts argument value.
			Opts CreateOptions
		}
		// Delete holds details about calls to the Delete method.
		Delete []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// BeanID is the beanID argument value.
			BeanID string
			// Force is the force argument value.
			Force bool
		}
		// Reopen holds details about calls to the Reopen method.
		Reopen []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// BeanID is the beanID argument value.
			BeanID string
		}
		// Update holds details about calls to the Update method.
		Update []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// BeanID is the beanID argument value.
			BeanID string
			// Opts is the opts argument value.
			Opts UpdateOptions
		}
	}
	lockAddComment    sync.RWMutex
	lockAddDependency sync.RWMutex
	lockAddTags       sync.RWMutex
	lockClose         sync.RWMutex
	lockCreate        sync.RWMutex
	lockDelete        sync.RWMutex
	lockReopen        sync.RWMutex
	lockUpdate        sync.RWMutex
}

// AddComment calls AddCommentFunc.
func (mock *BeansCLIMock) AddComment(ctx context.Context, beanID string, comment string) error {
	callInfo := struct {
		Ctx     context.Context
		BeanID  string
		Comment string
	}{
		Ctx:     ctx,
		BeanID:  beanID,
		Comment: comment,
	}
	mock.lockAddComment.Lock()
	mock.calls.AddComment = append(mock.calls.AddComment, callInfo)
	mock.lockAddComment.Unlock()
	if mock.AddCommentFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.AddCommentFunc(ctx, beanID, comment)
}

// AddCommentCalls gets all the calls that were made to AddComment.
// Check the length with:
//
//	len(mockedCLI.AddCommentCalls())
func (mock *BeansCLIMock) AddCommentCalls() []struct {
	Ctx     context.Context
	BeanID  string
	Comment string
} {
	var calls []struct {
		Ctx     context.Context
		BeanID  string
		Comment string
	}
	mock.lockAddComment.RLock()
	calls = mock.calls.AddComment
	mock.lockAddComment.RUnlock()
	return calls
}

// AddDependency calls AddDependencyFunc.
func (mock *BeansCLIMock) AddDependency(ctx context.Context, beanID string, dependsOnID string) error {
	callInfo := struct {
		Ctx         context.Context
		BeanID      string
		DependsOnID string
	}{
		Ctx:         ctx,
		BeanID:      beanID,
		DependsOnID: dependsOnID,
	}
	mock.lockAddDependency.Lock()
	mock.calls.AddDependency = append(mock.calls.AddDependency, callInfo)
	mock.lockAddDependency.Unlock()
	if mock.AddDependencyFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.AddDependencyFunc(ctx, beanID, dependsOnID)
}

// AddDependencyCalls gets all the calls that were made to AddDependency.
// Check the length with:
//
//	len(mockedCLI.AddDependencyCalls())
func (mock *BeansCLIMock) AddDependencyCalls() []struct {
	Ctx         context.Context
	BeanID      string
	DependsOnID string
} {
	var calls []struct {
		Ctx         context.Context
		BeanID      string
		DependsOnID string
	}
	mock.lockAddDependency.RLock()
	calls = mock.calls.AddDependency
	mock.lockAddDependency.RUnlock()
	return calls
}

// AddTags calls AddTagsFunc.
func (mock *BeansCLIMock) AddTags(ctx context.Context, beanID string, tags []string) error {
	callInfo := struct {
		Ctx    context.Context
		BeanID string
		Tags   []string
	}{
		Ctx:    ctx,
		BeanID: beanID,
		Tags:   tags,
	}
	mock.lockAddTags.Lock()
	mock.calls.AddTags = append(mock.calls.AddTags, callInfo)
	mock.lockAddTags.Unlock()
	if mock.AddTagsFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.AddTagsFunc(ctx, beanID, tags)
}

// AddTagsCalls gets all the calls that were made to AddTags.
// Check the length with:
//
//	len(mockedCLI.AddTagsCalls())
func (mock *BeansCLIMock) AddTagsCalls() []struct {
	Ctx    context.Context
	BeanID string
	Tags   []string
} {
	var calls []struct {
		Ctx    context.Context
		BeanID string
		Tags   []string
	}
	mock.lockAddTags.RLock()
	calls = mock.calls.AddTags
	mock.lockAddTags.RUnlock()
	return calls
}

// Close calls CloseFunc.
func (mock *BeansCLIMock) Close(ctx context.Context, beanID string) error {
	callInfo := struct {
		Ctx    context.Context
		BeanID string
	}{
		Ctx:    ctx,
		BeanID: beanID,
	}
	mock.lockClose.Lock()
	mock.calls.Close = append(mock.calls.Close, callInfo)
	mock.lockClose.Unlock()
	if mock.CloseFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.CloseFunc(ctx, beanID)
}

// CloseCalls gets all the calls that were made to Close.
// Check the length with:
//
//	len(mockedCLI.CloseCalls())
func (mock *BeansCLIMock) CloseCalls() []struct {
	Ctx    context.Context
	BeanID string
} {
	var calls []struct {
		Ctx    context.Context
		BeanID string
	}
	mock.lockClose.RLock()
	calls = mock.calls.Close
	mock.lockClose.RUnlock()
	return calls
}

// Create calls CreateFunc.
func (mock *BeansCLIMock) Create(ctx context.Context, opts CreateOptions) (string, error) {
	callInfo := struct {
		Ctx  context.Context
		Opts CreateOptions
	}{
		Ctx:  ctx,
		Opts: opts,
	}
	mock.lockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	mock.lockCreate.Unlock()
	if mock.CreateFunc == nil {
		var (
			sOut   string
			errOut error
		)
		return sOut, errOut
	}
	return mock.CreateFunc(ctx, opts)
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//
//	len(mockedCLI.CreateCalls())
func (mock *BeansCLIMock) CreateCalls() []struct {
	Ctx  context.Context
	Opts CreateOptions
} {
	var calls []struct {
		Ctx  context.Context
		Opts CreateOptions
	}
	mock.lockCreate.RLock()
	calls = mock.calls.Create
	mock.lockCreate.RUnlock()
	return calls
}

// Delete calls DeleteFunc.
func (mock *BeansCLIMock) Delete(ctx context.Context, beanID string, force bool) error {
	callInfo := struct {
		Ctx    context.Context
		BeanID string
		Force  bool
	}{
		Ctx:    ctx,
		BeanID: beanID,
		Force:  force,
	}
	mock.lockDelete.Lock()
	mock.calls.Delete = append(mock.calls.Delete, callInfo)
	mock.lockDelete.Unlock()
	if mock.DeleteFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.DeleteFunc(ctx, beanID, force)
}

// DeleteCalls gets all the calls that were made to Delete.
// Check the length with:
//
//	len(mockedCLI.DeleteCalls())
func (mock *BeansCLIMock) DeleteCalls() []struct {
	Ctx    context.Context
	BeanID string
	Force  bool
} {
	var calls []struct {
		Ctx    context.Context
		BeanID string
		Force  bool
	}
	mock.lockDelete.RLock()
	calls = mock.calls.Delete
	mock.lockDelete.RUnlock()
	return calls
}

// Reopen calls ReopenFunc.
func (mock *BeansCLIMock) Reopen(ctx context.Context, beanID string) error {
	callInfo := struct {
		Ctx    context.Context
		BeanID string
	}{
		Ctx:    ctx,
		BeanID: beanID,
	}
	mock.lockReopen.Lock()
	mock.calls.Reopen = append(mock.calls.Reopen, callInfo)
	mock.lockReopen.Unlock()
	if mock.ReopenFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.ReopenFunc(ctx, beanID)
}

// ReopenCalls gets all the calls that were made to Reopen.
// Check the length with:
//
//	len(mockedCLI.ReopenCalls())
func (mock *BeansCLIMock) ReopenCalls() []struct {
	Ctx    context.Context
	BeanID string
} {
	var calls []struct {
		Ctx    context.Context
		BeanID string
	}
	mock.lockReopen.RLock()
	calls = mock.calls.Reopen
	mock.lockReopen.RUnlock()
	return calls
}

// Update calls UpdateFunc.
func (mock *BeansCLIMock) Update(ctx context.Context, beanID string, opts UpdateOptions) error {
	callInfo := struct {
		Ctx    context.Context
		BeanID string
		Opts   UpdateOptions
	}{
		Ctx:    ctx,
		BeanID: beanID,
		Opts:   opts,
	}
	mock.lockUpdate.Lock()
	mock.calls.Update = append(mock.calls.Update, callInfo)
	mock.lockUpdate.Unlock()
	if mock.UpdateFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.UpdateFunc(ctx, beanID, opts)
}

// UpdateCalls gets all the calls that were made to Update.
// Check the length with:
//
//	len(mockedCLI.UpdateCalls())
func (mock *BeansCLIMock) UpdateCalls() []struct {
	Ctx    context.Context
	BeanID string
	Opts   UpdateOptions
} {
	var calls []struct {
		Ctx    context.Context
		BeanID string
		Opts   UpdateOptions
	}
	mock.lockUpdate.RLock()
	calls = mock.calls.Update
	mock.lockUpdate.RUnlock()
	return calls
}

// Ensure, that BeansReaderMock does implement Reader.
// If this is not the case, regenerate this file with moq.
var _ Reader = &BeansReaderMock{}

// BeansReaderMock is a mock implementation of Reader.
//
//	func TestSomethingThatUsesReader(t *testing.T) {
//
//		// make and configure a mocked Reader
//		mockedReader := &BeansReaderMock{
//			GetBeanFunc: func(ctx context.Context, id string) (*BeanWithDeps, error) {
//				panic("mock out the GetBean method")
//			},
//			GetBeanWithChildrenFunc: func(ctx context.Context, id string) ([]Bean, error) {
//				panic("mock out the GetBeanWithChildren method")
//			},
//			GetBeansWithDepsFunc: func(ctx context.Context, beanIDs []string) (*BeansWithDepsResult, error) {
//				panic("mock out the GetBeansWithDeps method")
//			},
//			GetReadyBeansFunc: func(ctx context.Context) ([]Bean, error) {
//				panic("mock out the GetReadyBeans method")
//			},
//			GetTransitiveDependenciesFunc: func(ctx context.Context, id string) ([]Bean, error) {
//				panic("mock out the GetTransitiveDependencies method")
//			},
//			ListBeansFunc: func(ctx context.Context, status string) ([]Bean, error) {
//				panic("mock out the ListBeans method")
//			},
//		}
//
//		// use mockedReader in code that requires Reader
//		// and then make assertions.
//
//	}
type BeansReaderMock struct {
	// GetBeanFunc mocks the GetBean method.
	GetBeanFunc func(ctx context.Context, id string) (*BeanWithDeps, error)

	// GetBeanWithChildrenFunc mocks the GetBeanWithChildren method.
	GetBeanWithChildrenFunc func(ctx context.Context, id string) ([]Bean, error)

	// GetBeansWithDepsFunc mocks the GetBeansWithDeps method.
	GetBeansWithDepsFunc func(ctx context.Context, beanIDs []string) (*BeansWithDepsResult, error)

	// GetReadyBeansFunc mocks the GetReadyBeans method.
	GetReadyBeansFunc func(ctx context.Context) ([]Bean, error)

	// GetTransitiveDependenciesFunc mocks the GetTransitiveDependencies method.
	GetTransitiveDependenciesFunc func(ctx context.Context, id string) ([]Bean, error)

	// ListBeansFunc mocks the ListBeans method.
	ListBeansFunc func(ctx context.Context, status string) ([]Bean, error)

	// calls tracks calls to the methods.
	calls struct {
		// GetBean holds details about calls to the GetBean method.
		GetBean []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID string
		}
		// GetBeanWithChildren holds details about calls to the GetBeanWithChildren method.
		GetBeanWithChildren []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID string
		}
		// GetBeansWithDeps holds details about calls to the GetBeansWithDeps method.
		GetBeansWithDeps []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// BeanIDs is the beanIDs argument value.
			BeanIDs []string
		}
		// GetReadyBeans holds details about calls to the GetReadyBeans method.
		GetReadyBeans []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// GetTransitiveDependencies holds details about calls to the GetTransitiveDependencies method.
		GetTransitiveDependencies []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID string
		}
		// ListBeans holds details about calls to the ListBeans method.
		ListBeans []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Status is the status argument value.
			Status string
		}
	}
	lockGetBean                   sync.RWMutex
	lockGetBeanWithChildren       sync.RWMutex
	lockGetBeansWithDeps          sync.RWMutex
	lockGetReadyBeans             sync.RWMutex
	lockGetTransitiveDependencies sync.RWMutex
	lockListBeans                 sync.RWMutex
}

// GetBean calls GetBeanFunc.
func (mock *BeansReaderMock) GetBean(ctx context.Context, id string) (*BeanWithDeps, error) {
	callInfo := struct {
		Ctx context.Context
		ID  string
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockGetBean.Lock()
	mock.calls.GetBean = append(mock.calls.GetBean, callInfo)
	mock.lockGetBean.Unlock()
	if mock.GetBeanFunc == nil {
		var (
			beanWithDepsOut *BeanWithDeps
			errOut          error
		)
		return beanWithDepsOut, errOut
	}
	return mock.GetBeanFunc(ctx, id)
}

// GetBeanCalls gets all the calls that were made to GetBean.
// Check the length with:
//
//	len(mockedReader.GetBeanCalls())
func (mock *BeansReaderMock) GetBeanCalls() []struct {
	Ctx context.Context
	ID  string
} {
	var calls []struct {
		Ctx context.Context
		ID  string
	}
	mock.lockGetBean.RLock()
	calls = mock.calls.GetBean
	mock.lockGetBean.RUnlock()
	return calls
}

// GetBeanWithChildren calls GetBeanWithChildrenFunc.
func (mock *BeansReaderMock) GetBeanWithChildren(ctx context.Context, id string) ([]Bean, error) {
	callInfo := struct {
		Ctx context.Context
		ID  string
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockGetBeanWithChildren.Lock()
	mock.calls.GetBeanWithChildren = append(mock.calls.GetBeanWithChildren, callInfo)
	mock.lockGetBeanWithChildren.Unlock()
	if mock.GetBeanWithChildrenFunc == nil {
		var (
			beansOut []Bean
			errOut   error
		)
		return beansOut, errOut
	}
	return mock.GetBeanWithChildrenFunc(ctx, id)
}

// GetBeanWithChildrenCalls gets all the calls that were made to GetBeanWithChildren.
// Check the length with:
//
//	len(mockedReader.GetBeanWithChildrenCalls())
func (mock *BeansReaderMock) GetBeanWithChildrenCalls() []struct {
	Ctx context.Context
	ID  string
} {
	var calls []struct {
		Ctx context.Context
		ID  string
	}
	mock.lockGetBeanWithChildren.RLock()
	calls = mock.calls.GetBeanWithChildren
	mock.lockGetBeanWithChildren.RUnlock()
	return calls
}

// GetBeansWithDeps calls GetBeansWithDepsFunc.
func (mock *BeansReaderMock) GetBeansWithDeps(ctx context.Context, beanIDs []string) (*BeansWithDepsResult, error) {
	callInfo := struct {
		Ctx     context.Context
		BeanIDs []string
	}{
		Ctx:     ctx,
		BeanIDs: beanIDs,
	}
	mock.lockGetBeansWithDeps.Lock()
	mock.calls.GetBeansWithDeps = append(mock.calls.GetBeansWithDeps, callInfo)
	mock.lockGetBeansWithDeps.Unlock()
	if mock.GetBeansWithDepsFunc == nil {
		var (
			beansWithDepsResultOut *BeansWithDepsResult
			errOut                 error
		)
		return beansWithDepsResultOut, errOut
	}
	return mock.GetBeansWithDepsFunc(ctx, beanIDs)
}

// GetBeansWithDepsCalls gets all the calls that were made to GetBeansWithDeps.
// Check the length with:
//
//	len(mockedReader.GetBeansWithDepsCalls())
func (mock *BeansReaderMock) GetBeansWithDepsCalls() []struct {
	Ctx     context.Context
	BeanIDs []string
} {
	var calls []struct {
		Ctx     context.Context
		BeanIDs []string
	}
	mock.lockGetBeansWithDeps.RLock()
	calls = mock.calls.GetBeansWithDeps
	mock.lockGetBeansWithDeps.RUnlock()
	return calls
}

// GetReadyBeans calls GetReadyBeansFunc.
func (mock *BeansReaderMock) GetReadyBeans(ctx context.Context) ([]Bean, error) {
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockGetReadyBeans.Lock()
	mock.calls.GetReadyBeans = append(mock.calls.GetReadyBeans, callInfo)
	mock.lockGetReadyBeans.Unlock()
	if mock.GetReadyBeansFunc == nil {
		var (
			beansOut []Bean
			errOut   error
		)
		return beansOut, errOut
	}
	return mock.GetReadyBeansFunc(ctx)
}

// GetReadyBeansCalls gets all the calls that were made to GetReadyBeans.
// Check the length with:
//
//	len(mockedReader.GetReadyBeansCalls())
func (mock *BeansReaderMock) GetReadyBeansCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockGetReadyBeans.RLock()
	calls = mock.calls.GetReadyBeans
	mock.lockGetReadyBeans.RUnlock()
	return calls
}

// GetTransitiveDependencies calls GetTransitiveDependenciesFunc.
func (mock *BeansReaderMock) GetTransitiveDependencies(ctx context.Context, id string) ([]Bean, error) {
	callInfo := struct {
		Ctx context.Context
		ID  string
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockGetTransitiveDependencies.Lock()
	mock.calls.GetTransitiveDependencies = append(mock.calls.GetTransitiveDependencies, callInfo)
	mock.lockGetTransitiveDependencies.Unlock()
	if mock.GetTransitiveDependenciesFunc == nil {
		var (
			beansOut []Bean
			errOut   error
		)
		return beansOut, errOut
	}
	return mock.GetTransitiveDependenciesFunc(ctx, id)
}

// GetTransitiveDependenciesCalls gets all the calls that were made to GetTransitiveDependencies.
// Check the length with:
//
//	len(mockedReader.GetTransitiveDependenciesCalls())
func (mock *BeansReaderMock) GetTransitiveDependenciesCalls() []struct {
	Ctx context.Context
	ID  string
} {
	var calls []struct {
		Ctx context.Context
		ID  string
	}
	mock.lockGetTransitiveDependencies.RLock()
	calls = mock.calls.GetTransitiveDependencies
	mock.lockGetTransitiveDependencies.RUnlock()
	return calls
}

// ListBeans calls ListBeansFunc.
func (mock *BeansReaderMock) ListBeans(ctx context.Context, status string) ([]Bean, error) {
	callInfo := struct {
		Ctx    context.Context
		Status string
	}{
		Ctx:    ctx,
		Status: status,
	}
	mock.lockListBeans.Lock()
	mock.calls.ListBeans = append(mock.calls.ListBeans, callInfo)
	mock.lockListBeans.Unlock()
	if mock.ListBeansFunc == nil {
		var (
			beansOut []Bean
			errOut   error
		)
		return beansOut, errOut
	}
	return mock.ListBeansFunc(ctx, status)
}

// ListBeansCalls gets all the calls that were made to ListBeans.
// Check the length with:
//
//	len(mockedReader.ListBeansCalls())
func (mock *BeansReaderMock) ListBeansCalls() []struct {
	Ctx    context.Context
	Status string
} {
	var calls []struct {
		Ctx    context.Context
		Status string
	}
	mock.lockListBeans.RLock()
	calls = mock.calls.ListBeans
	mock.lockListBeans.RUnlock()
	return calls
}
