// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package work

import (
	"context"
	"github.com/sargehq/sarge/internal/ptysession"
	"github.com/sargehq/sarge/internal/project"
	"io"
	"sync"
)

// Ensure, that OrchestratorManagerMock does implement OrchestratorManager.
// If this is not the case, regenerate this file with moq.
var _ OrchestratorManager = &OrchestratorManagerMock{}

// OrchestratorManagerMock is a mock implementation of OrchestratorManager.
//
//	func TestSomethingThatUsesOrchestratorManager(t *testing.T) {
//
//		// make and configure a mocked OrchestratorManager
//		mockedOrchestratorManager := &OrchestratorManagerMock{
//			AttachToSessionFunc: func(ctx context.Context, sessionName string) error {
//				panic("mock out the AttachToSession method")
//			},
//			EnsureWorkOrchestratorFunc: func(ctx context.Context, workID string, projName string, workDir string, friendlyName string, w io.Writer) (bool, error) {
//				panic("mock out the EnsureWorkOrchestrator method")
//			},
//			ListWorkSessionsFunc: func(ctx context.Context, workID string, projectName string) ([]WorkSession, error) {
//				panic("mock out the ListWorkSessions method")
//			},
//			OpenAgentSessionFunc: func(ctx context.Context, workID string, projName string, workDir string, friendlyName string, hooksEnv []string, cfg *project.Config, w io.Writer) (*ptysession.Session, error) {
//				panic("mock out the OpenAgentSession method")
//			},
//			OpenConsoleFunc: func(ctx context.Context, workID string, projName string, workDir string, friendlyName string, hooksEnv []string, w io.Writer) error {
//				panic("mock out the OpenConsole method")
//			},
//			SpawnPlanSessionFunc: func(ctx context.Context, beanID string, projName string, mainRepoPath string, w io.Writer) (*ptysession.Session, error) {
//				panic("mock out the SpawnPlanSession method")
//			},
//			SpawnWorkOrchestratorFunc: func(ctx context.Context, workID string, projName string, workDir string, friendlyName string, w io.Writer) error {
//				panic("mock out the SpawnWorkOrchestrator method")
//			},
//			TerminateWorkTabsFunc: func(ctx context.Context, workID string, projName string, w io.Writer) error {
//				panic("mock out the TerminateWorkTabs method")
//			},
//		}
//
//		// use mockedOrchestratorManager in code that requires OrchestratorManager
//		// and then make assertions.
//
//	}
type OrchestratorManagerMock struct {
	// AttachToSessionFunc mocks the AttachToSession method.
	AttachToSessionFunc func(ctx context.Context, sessionName string) error

	// EnsureWorkOrchestratorFunc mocks the EnsureWorkOrchestrator method.
	EnsureWorkOrchestratorFunc func(ctx context.Context, workID string, projName string, workDir string, friendlyName string, w io.Writer) (bool, error)

	// ListWorkSessionsFunc mocks the ListWorkSessions method.
	ListWorkSessionsFunc func(ctx context.Context, workID string, projectName string) ([]WorkSession, error)

	// OpenAgentSessionFunc mocks the OpenAgentSession method.
	OpenAgentSessionFunc func(ctx context.Context, workID string, projName string, workDir string, friendlyName string, hooksEnv []string, cfg *project.Config, w io.Writer) (*ptysession.Session, error)

	// OpenConsoleFunc mocks the OpenConsole method.
	OpenConsoleFunc func(ctx context.Context, workID string, projName string, workDir string, friendlyName string, hooksEnv []string, w io.Writer) error

	// SpawnPlanSessionFunc mocks the SpawnPlanSession method.
	SpawnPlanSessionFunc func(ctx context.Context, beanID string, projName string, mainRepoPath string, w io.Writer) (*ptysession.Session, error)

	// SpawnWorkOrchestratorFunc mocks the SpawnWorkOrchestrator method.
	SpawnWorkOrchestratorFunc func(ctx context.Context, workID string, projName string, workDir string, friendlyName string, w io.Writer) error

	// TerminateWorkTabsFunc mocks the TerminateWorkTabs method.
	TerminateWorkTabsFunc func(ctx context.Context, workID string, projName string, w io.Writer) error

	// calls tracks calls to the methods.
	calls struct {
		// AttachToSession holds details about calls to the AttachToSession method.
		AttachToSession []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// SessionName is the sessionName argument value.
			SessionName string
		}
		// EnsureWorkOrchestrator holds details about calls to the EnsureWorkOrchestrator method.
		EnsureWorkOrchestrator []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// WorkID is the workID argument value.
			WorkID string
			// ProjName is the projName argument value.
			ProjName string
			// WorkDir is the workDir argument value.
			WorkDir string
			// FriendlyName is the friendlyName argument value.
			FriendlyName string
			// W is the w argument value.
			W io.Writer
		}
		// ListWorkSessions holds details about calls to the ListWorkSessions method.
		ListWorkSessions []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// WorkID is the workID argument value.
			WorkID string
			// ProjectName is the projectName argument value.
			ProjectName string
		}
		// OpenAgentSession holds details about calls to the OpenAgentSession method.
		OpenAgentSession []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// WorkID is the workID argument value.
			WorkID string
			// ProjName is the projName argument value.
			ProjName string
			// WorkDir is the workDir argument value.
			WorkDir string
			// FriendlyName is the friendlyName argument value.
			FriendlyName string
			// HooksEnv is the hooksEnv argument value.
			HooksEnv []string
			// Cfg is the cfg argument value.
			Cfg *project.Config
			// W is the w argument value.
			W io.Writer
		}
		// OpenConsole holds details about calls to the OpenConsole method.
		OpenConsole []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// WorkID is the workID argument value.
			WorkID string
			// ProjName is the projName argument value.
			ProjName string
			// WorkDir is the workDir argument value.
			WorkDir string
			// FriendlyName is the friendlyName argument value.
			FriendlyName string
			// HooksEnv is the hooksEnv argument value.
			HooksEnv []string
			// W is the w argument value.
			W io.Writer
		}
		// SpawnPlanSession holds details about calls to the SpawnPlanSession method.
		SpawnPlanSession []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// BeanID is the beanID argument value.
			BeanID string
			// ProjName is the projName argument value.
			ProjName string
			// MainRepoPath is the mainRepoPath argument value.
			MainRepoPath string
			// W is the w argument value.
			W io.Writer
		}
		// SpawnWorkOrchestrator holds details about calls to the SpawnWorkOrchestrator method.
		SpawnWorkOrchestrator []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// WorkID is the workID argument value.
			WorkID string
			// ProjName is the projName argument value.
			ProjName string
			// WorkDir is the workDir argument value.
			WorkDir string
			// FriendlyName is the friendlyName argument value.
			FriendlyName string
			// W is the w argument value.
			W io.Writer
		}
		// TerminateWorkTabs holds details about calls to the TerminateWorkTabs method.
		TerminateWorkTabs []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// WorkID is the workID argument value.
			WorkID string
			// ProjName is the projName argument value.
			ProjName string
			// W is the w argument value.
			W io.Writer
		}
	}
	lockAttachToSession        sync.RWMutex
	lockEnsureWorkOrchestrator sync.RWMutex
	lockListWorkSessions       sync.RWMutex
	lockOpenAgentSession       sync.RWMutex
	lockOpenConsole            sync.RWMutex
	lockSpawnPlanSession       sync.RWMutex
	lockSpawnWorkOrchestrator  sync.RWMutex
	lockTerminateWorkTabs      sync.RWMutex
}

// AttachToSession calls AttachToSessionFunc.
func (mock *OrchestratorManagerMock) AttachToSession(ctx context.Context, sessionName string) error {
	callInfo := struct {
		Ctx         context.Context
		SessionName string
	}{
		Ctx:         ctx,
		SessionName: sessionName,
	}
	mock.lockAttachToSession.Lock()
	mock.calls.AttachToSession = append(mock.calls.AttachToSession, callInfo)
	mock.lockAttachToSession.Unlock()
	if mock.AttachToSessionFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.AttachToSessionFunc(ctx, sessionName)
}

// AttachToSessionCalls gets all the calls that were made to AttachToSession.
// Check the length with:
//
//	len(mockedOrchestratorManager.AttachToSessionCalls())
func (mock *OrchestratorManagerMock) AttachToSessionCalls() []struct {
	Ctx         context.Context
	SessionName string
} {
	var calls []struct {
		Ctx         context.Context
		SessionName string
	}
	mock.lockAttachToSession.RLock()
	calls = mock.calls.AttachToSession
	mock.lockAttachToSession.RUnlock()
	return calls
}

// EnsureWorkOrchestrator calls EnsureWorkOrchestratorFunc.
func (mock *OrchestratorManagerMock) EnsureWorkOrchestrator(ctx context.Context, workID string, projName string, workDir string, friendlyName string, w io.Writer) (bool, error) {
	callInfo := struct {
		Ctx          context.Context
		WorkID       string
		ProjName     string
		WorkDir      string
		FriendlyName string
		W            io.Writer
	}{
		Ctx:          ctx,
		WorkID:       workID,
		ProjName:     projName,
		WorkDir:      workDir,
		FriendlyName: friendlyName,
		W:            w,
	}
	mock.lockEnsureWorkOrchestrator.Lock()
	mock.calls.EnsureWorkOrchestrator = append(mock.calls.EnsureWorkOrchestrator, callInfo)
	mock.lockEnsureWorkOrchestrator.Unlock()
	if mock.EnsureWorkOrchestratorFunc == nil {
		var (
			bOut   bool
			errOut error
		)
		return bOut, errOut
	}
	return mock.EnsureWorkOrchestratorFunc(ctx, workID, projName, workDir, friendlyName, w)
}

// EnsureWorkOrchestratorCalls gets all the calls that were made to EnsureWorkOrchestrator.
// Check the length with:
//
//	len(mockedOrchestratorManager.EnsureWorkOrchestratorCalls())
func (mock *OrchestratorManagerMock) EnsureWorkOrchestratorCalls() []struct {
	Ctx          context.Context
	WorkID       string
	ProjName     string
	WorkDir      string
	FriendlyName string
	W            io.Writer
} {
	var calls []struct {
		Ctx          context.Context
		WorkID       string
		ProjName     string
		WorkDir      string
		FriendlyName string
		W            io.Writer
	}
	mock.lockEnsureWorkOrchestrator.RLock()
	calls = mock.calls.EnsureWorkOrchestrator
	mock.lockEnsureWorkOrchestrator.RUnlock()
	return calls
}

// ListWorkSessions calls ListWorkSessionsFunc.
func (mock *OrchestratorManagerMock) ListWorkSessions(ctx context.Context, workID string, projectName string) ([]WorkSession, error) {
	callInfo := struct {
		Ctx         context.Context
		WorkID      string
		ProjectName string
	}{
		Ctx:         ctx,
		WorkID:      workID,
		ProjectName: projectName,
	}
	mock.lockListWorkSessions.Lock()
	mock.calls.ListWorkSessions = append(mock.calls.ListWorkSessions, callInfo)
	mock.lockListWorkSessions.Unlock()
	if mock.ListWorkSessionsFunc == nil {
		var (
			workSessionsOut []WorkSession
			errOut          error
		)
		return workSessionsOut, errOut
	}
	return mock.ListWorkSessionsFunc(ctx, workID, projectName)
}

// ListWorkSessionsCalls gets all the calls that were made to ListWorkSessions.
// Check the length with:
//
//	len(mockedOrchestratorManager.ListWorkSessionsCalls())
func (mock *OrchestratorManagerMock) ListWorkSessionsCalls() []struct {
	Ctx         context.Context
	WorkID      string
	ProjectName string
} {
	var calls []struct {
		Ctx         context.Context
		WorkID      string
		ProjectName string
	}
	mock.lockListWorkSessions.RLock()
	calls = mock.calls.ListWorkSessions
	mock.lockListWorkSessions.RUnlock()
	return calls
}

// OpenAgentSession calls OpenAgentSessionFunc.
func (mock *OrchestratorManagerMock) OpenAgentSession(ctx context.Context, workID string, projName string, workDir string, friendlyName string, hooksEnv []string, cfg *project.Config, w io.Writer) (*ptysession.Session, error) {
	callInfo := struct {
		Ctx          context.Context
		WorkID       string
		ProjName     string
		WorkDir      string
		FriendlyName string
		HooksEnv     []string
		Cfg          *project.Config
		W            io.Writer
	}{
		Ctx:          ctx,
		WorkID:       workID,
		ProjName:     projName,
		WorkDir:      workDir,
		FriendlyName: friendlyName,
		HooksEnv:     hooksEnv,
		Cfg:          cfg,
		W:            w,
	}
	mock.lockOpenAgentSession.Lock()
	mock.calls.OpenAgentSession = append(mock.calls.OpenAgentSession, callInfo)
	mock.lockOpenAgentSession.Unlock()
	if mock.OpenAgentSessionFunc == nil {
		var (
			sessionOut *ptysession.Session
			errOut     error
		)
		return sessionOut, errOut
	}
	return mock.OpenAgentSessionFunc(ctx, workID, projName, workDir, friendlyName, hooksEnv, cfg, w)
}

// OpenAgentSessionCalls gets all the calls that were made to OpenAgentSession.
// Check the length with:
//
//	len(mockedOrchestratorManager.OpenAgentSessionCalls())
func (mock *OrchestratorManagerMock) OpenAgentSessionCalls() []struct {
	Ctx          context.Context
	WorkID       string
	ProjName     string
	WorkDir      string
	FriendlyName string
	HooksEnv     []string
	Cfg          *project.Config
	W            io.Writer
} {
	var calls []struct {
		Ctx          context.Context
		WorkID       string
		ProjName     string
		WorkDir      string
		FriendlyName string
		HooksEnv     []string
		Cfg          *project.Config
		W            io.Writer
	}
	mock.lockOpenAgentSession.RLock()
	calls = mock.calls.OpenAgentSession
	mock.lockOpenAgentSession.RUnlock()
	return calls
}

// OpenConsole calls OpenConsoleFunc.
func (mock *OrchestratorManagerMock) OpenConsole(ctx context.Context, workID string, projName string, workDir string, friendlyName string, hooksEnv []string, w io.Writer) error {
	callInfo := struct {
		Ctx          context.Context
		WorkID       string
		ProjName     string
		WorkDir      string
		FriendlyName string
		HooksEnv     []string
		W            io.Writer
	}{
		Ctx:          ctx,
		WorkID:       workID,
		ProjName:     projName,
		WorkDir:      workDir,
		FriendlyName: friendlyName,
		HooksEnv:     hooksEnv,
		W:            w,
	}
	mock.lockOpenConsole.Lock()
	mock.calls.OpenConsole = append(mock.calls.OpenConsole, callInfo)
	mock.lockOpenConsole.Unlock()
	if mock.OpenConsoleFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.OpenConsoleFunc(ctx, workID, projName, workDir, friendlyName, hooksEnv, w)
}

// OpenConsoleCalls gets all the calls that were made to OpenConsole.
// Check the length with:
//
//	len(mockedOrchestratorManager.OpenConsoleCalls())
func (mock *OrchestratorManagerMock) OpenConsoleCalls() []struct {
	Ctx          context.Context
	WorkID       string
	ProjName     string
	WorkDir      string
	FriendlyName string
	HooksEnv     []string
	W            io.Writer
} {
	var calls []struct {
		Ctx          context.Context
		WorkID       string
		ProjName     string
		WorkDir      string
		FriendlyName string
		HooksEnv     []string
		W            io.Writer
	}
	mock.lockOpenConsole.RLock()
	calls = mock.calls.OpenConsole
	mock.lockOpenConsole.RUnlock()
	return calls
}

// SpawnPlanSession calls SpawnPlanSessionFunc.
func (mock *OrchestratorManagerMock) SpawnPlanSession(ctx context.Context, beanID string, projName string, mainRepoPath string, w io.Writer) (*ptysession.Session, error) {
	callInfo := struct {
		Ctx          context.Context
		BeanID       string
		ProjName     string
		MainRepoPath string
		W            io.Writer
	}{
		Ctx:          ctx,
		BeanID:       beanID,
		ProjName:     projName,
		MainRepoPath: mainRepoPath,
		W:            w,
	}
	mock.lockSpawnPlanSession.Lock()
	mock.calls.SpawnPlanSession = append(mock.calls.SpawnPlanSession, callInfo)
	mock.lockSpawnPlanSession.Unlock()
	if mock.SpawnPlanSessionFunc == nil {
		var (
			sessionOut *ptysession.Session
			errOut     error
		)
		return sessionOut, errOut
	}
	return mock.SpawnPlanSessionFunc(ctx, beanID, projName, mainRepoPath, w)
}

// SpawnPlanSessionCalls gets all the calls that were made to SpawnPlanSession.
// Check the length with:
//
//	len(mockedOrchestratorManager.SpawnPlanSessionCalls())
func (mock *OrchestratorManagerMock) SpawnPlanSessionCalls() []struct {
	Ctx          context.Context
	BeanID       string
	ProjName     string
	MainRepoPath string
	W            io.Writer
} {
	var calls []struct {
		Ctx          context.Context
		BeanID       string
		ProjName     string
		MainRepoPath string
		W            io.Writer
	}
	mock.lockSpawnPlanSession.RLock()
	calls = mock.calls.SpawnPlanSession
	mock.lockSpawnPlanSession.RUnlock()
	return calls
}

// SpawnWorkOrchestrator calls SpawnWorkOrchestratorFunc.
func (mock *OrchestratorManagerMock) SpawnWorkOrchestrator(ctx context.Context, workID string, projName string, workDir string, friendlyName string, w io.Writer) error {
	callInfo := struct {
		Ctx          context.Context
		WorkID       string
		ProjName     string
		WorkDir      string
		FriendlyName string
		W            io.Writer
	}{
		Ctx:          ctx,
		WorkID:       workID,
		ProjName:     projName,
		WorkDir:      workDir,
		FriendlyName: friendlyName,
		W:            w,
	}
	mock.lockSpawnWorkOrchestrator.Lock()
	mock.calls.SpawnWorkOrchestrator = append(mock.calls.SpawnWorkOrchestrator, callInfo)
	mock.lockSpawnWorkOrchestrator.Unlock()
	if mock.SpawnWorkOrchestratorFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.SpawnWorkOrchestratorFunc(ctx, workID, projName, workDir, friendlyName, w)
}

// SpawnWorkOrchestratorCalls gets all the calls that were made to SpawnWorkOrchestrator.
// Check the length with:
//
//	len(mockedOrchestratorManager.SpawnWorkOrchestratorCalls())
func (mock *OrchestratorManagerMock) SpawnWorkOrchestratorCalls() []struct {
	Ctx          context.Context
	WorkID       string
	ProjName     string
	WorkDir      string
	FriendlyName string
	W            io.Writer
} {
	var calls []struct {
		Ctx          context.Context
		WorkID       string
		ProjName     string
		WorkDir      string
		FriendlyName string
		W            io.Writer
	}
	mock.lockSpawnWorkOrchestrator.RLock()
	calls = mock.calls.SpawnWorkOrchestrator
	mock.lockSpawnWorkOrchestrator.RUnlock()
	return calls
}

// TerminateWorkTabs calls TerminateWorkTabsFunc.
func (mock *OrchestratorManagerMock) TerminateWorkTabs(ctx context.Context, workID string, projName string, w io.Writer) error {
	callInfo := struct {
		Ctx      context.Context
		WorkID   string
		ProjName string
		W        io.Writer
	}{
		Ctx:      ctx,
		WorkID:   workID,
		ProjName: projName,
		W:        w,
	}
	mock.lockTerminateWorkTabs.Lock()
	mock.calls.TerminateWorkTabs = append(mock.calls.TerminateWorkTabs, callInfo)
	mock.lockTerminateWorkTabs.Unlock()
	if mock.TerminateWorkTabsFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.TerminateWorkTabsFunc(ctx, workID, projName, w)
}

// TerminateWorkTabsCalls gets all the calls that were made to TerminateWorkTabs.
// Check the length with:
//
//	len(mockedOrchestratorManager.TerminateWorkTabsCalls())
func (mock *OrchestratorManagerMock) TerminateWorkTabsCalls() []struct {
	Ctx      context.Context
	WorkID   string
	ProjName string
	W        io.Writer
} {
	var calls []struct {
		Ctx      context.Context
		WorkID   string
		ProjName string
		W        io.Writer
	}
	mock.lockTerminateWorkTabs.RLock()
	calls = mock.calls.TerminateWorkTabs
	mock.lockTerminateWorkTabs.RUnlock()
	return calls
}
