// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package agents

import (
	"context"
	"github.com/sargehq/sarge/internal/agents/types"
	"github.com/sargehq/sarge/internal/db"
	"github.com/sargehq/sarge/internal/project"
	"io"
	"sync"
)

// Ensure, that AgentMock does implement Agent.
// If this is not the case, regenerate this file with moq.
var _ Agent = &AgentMock{}

// AgentMock is a mock implementation of Agent.
//
//	func TestSomethingThatUsesAgent(t *testing.T) {
//
//		// make and configure a mocked Agent
//		mockedAgent := &AgentMock{
//			BuildPromptFunc: func(params types.TaskParams) (string, error) {
//				panic("mock out the BuildPrompt method")
//			},
//			RunFunc: func(ctx context.Context, database *db.DB, taskID string, prompt string, workDir string, cfg *project.Config) error {
//				panic("mock out the Run method")
//			},
//			RunInteractiveFunc: func(ctx context.Context, prompt string, workDir string, stdin io.Reader, stdout io.Writer, stderr io.Writer, cfg *project.Config) error {
//				panic("mock out the RunInteractive method")
//			},
//		}
//
//		// use mockedAgent in code that requires Agent
//		// and then make assertions.
//
//	}
type AgentMock struct {
	// BuildPromptFunc mocks the BuildPrompt method.
	BuildPromptFunc func(params types.TaskParams) (string, error)

	// RunFunc mocks the Run method.
	RunFunc func(ctx context.Context, database *db.DB, taskID string, prompt string, workDir string, cfg *project.Config) error

	// RunInteractiveFunc mocks the RunInteractive method.
	RunInteractiveFunc func(ctx context.Context, prompt string, workDir string, stdin io.Reader, stdout io.Writer, stderr io.Writer, cfg *project.Config) error

	// calls tracks calls to the methods.
	calls struct {
		// BuildPrompt holds details about calls to the BuildPrompt method.
		BuildPrompt []struct {
			// Params is the params argument value.
			Params types.TaskParams
		}
		// Run holds details about calls to the Run method.
		Run []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Database is the database argument value.
			Database *db.DB
			// TaskID is the taskID argument value.
			TaskID string
			// Prompt is the prompt argument value.
			Prompt string
			// WorkDir is the workDir argument value.
			WorkDir string
			// Cfg is the cfg argument value.
			Cfg *project.Config
		}
		// RunInteractive holds details about calls to the RunInteractive method.
		RunInteractive []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Prompt is the prompt argument value.
			Prompt string
			// WorkDir is the workDir argument value.
			WorkDir string
			// Stdin is the stdin argument value.
			Stdin io.Reader
			// Stdout is the stdout argument value.
			Stdout io.Writer
			// Stderr is the stderr argument value.
			Stderr io.Writer
			// Cfg is the cfg argument value.
			Cfg *project.Config
		}
	}
	lockBuildPrompt    sync.RWMutex
	lockRun            sync.RWMutex
	lockRunInteractive sync.RWMutex
}

// BuildPrompt calls BuildPromptFunc.
func (mock *AgentMock) BuildPrompt(params types.TaskParams) (string, error) {
	callInfo := struct {
		Params types.TaskParams
	}{
		Params: params,
	}
	mock.lockBuildPrompt.Lock()
	mock.calls.BuildPrompt = append(mock.calls.BuildPrompt, callInfo)
	mock.lockBuildPrompt.Unlock()
	if mock.BuildPromptFunc == nil {
		var (
			sOut   string
			errOut error
		)
		return sOut, errOut
	}
	return mock.BuildPromptFunc(params)
}

// BuildPromptCalls gets all the calls that were made to BuildPrompt.
// Check the length with:
//
//	len(mockedAgent.BuildPromptCalls())
func (mock *AgentMock) BuildPromptCalls() []struct {
	Params types.TaskParams
} {
	var calls []struct {
		Params types.TaskParams
	}
	mock.lockBuildPrompt.RLock()
	calls = mock.calls.BuildPrompt
	mock.lockBuildPrompt.RUnlock()
	return calls
}

// Run calls RunFunc.
func (mock *AgentMock) Run(ctx context.Context, database *db.DB, taskID string, prompt string, workDir string, cfg *project.Config) error {
	callInfo := struct {
		Ctx      context.Context
		Database *db.DB
		TaskID   string
		Prompt   string
		WorkDir  string
		Cfg      *project.Config
	}{
		Ctx:      ctx,
		Database: database,
		TaskID:   taskID,
		Prompt:   prompt,
		WorkDir:  workDir,
		Cfg:      cfg,
	}
	mock.lockRun.Lock()
	mock.calls.Run = append(mock.calls.Run, callInfo)
	mock.lockRun.Unlock()
	if mock.RunFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.RunFunc(ctx, database, taskID, prompt, workDir, cfg)
}

// RunCalls gets all the calls that were made to Run.
// Check the length with:
//
//	len(mockedAgent.RunCalls())
func (mock *AgentMock) RunCalls() []struct {
	Ctx      context.Context
	Database *db.DB
	TaskID   string
	Prompt   string
	WorkDir  string
	Cfg      *project.Config
} {
	var calls []struct {
		Ctx      context.Context
		Database *db.DB
		TaskID   string
		Prompt   string
		WorkDir  string
		Cfg      *project.Config
	}
	mock.lockRun.RLock()
	calls = mock.calls.Run
	mock.lockRun.RUnlock()
	return calls
}

// RunInteractive calls RunInteractiveFunc.
func (mock *AgentMock) RunInteractive(ctx context.Context, prompt string, workDir string, stdin io.Reader, stdout io.Writer, stderr io.Writer, cfg *project.Config) error {
	callInfo := struct {
		Ctx     context.Context
		Prompt  string
		WorkDir string
		Stdin   io.Reader
		Stdout  io.Writer
		Stderr  io.Writer
		Cfg     *project.Config
	}{
		Ctx:     ctx,
		Prompt:  prompt,
		WorkDir: workDir,
		Stdin:   stdin,
		Stdout:  stdout,
		Stderr:  stderr,
		Cfg:     cfg,
	}
	mock.lockRunInteractive.Lock()
	mock.calls.RunInteractive = append(mock.calls.RunInteractive, callInfo)
	mock.lockRunInteractive.Unlock()
	if mock.RunInteractiveFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.RunInteractiveFunc(ctx, prompt, workDir, stdin, stdout, stderr, cfg)
}

// RunInteractiveCalls gets all the calls that were made to RunInteractive.
// Check the length with:
//
//	len(mockedAgent.RunInteractiveCalls())
func (mock *AgentMock) RunInteractiveCalls() []struct {
	Ctx     context.Context
	Prompt  string
	WorkDir string
	Stdin   io.Reader
	Stdout  io.Writer
	Stderr  io.Writer
	Cfg     *project.Config
} {
	var calls []struct {
		Ctx     context.Context
		Prompt  string
		WorkDir string
		Stdin   io.Reader
		Stdout  io.Writer
		Stderr  io.Writer
		Cfg     *project.Config
	}
	mock.lockRunInteractive.RLock()
	calls = mock.calls.RunInteractive
	mock.lockRunInteractive.RUnlock()
	return calls
}
