// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package zmx

import (
	"context"
	"sync"
)

// Ensure, that ClientMock does implement Client.
// If this is not the case, regenerate this file with moq.
var _ Client = &ClientMock{}

// ClientMock is a mock implementation of Client.
//
//	func TestSomethingThatUsesClient(t *testing.T) {
//
//		// make and configure a mocked Client
//		mockedClient := &ClientMock{
//			AttachSessionFunc: func(ctx context.Context, name string, terminalCmdTemplate string) error {
//				panic("mock out the AttachSession method")
//			},
//			KillSessionFunc: func(ctx context.Context, name string) error {
//				panic("mock out the KillSession method")
//			},
//			ListSessionsFunc: func(ctx context.Context, prefix string) ([]string, error) {
//				panic("mock out the ListSessions method")
//			},
//			RunSessionFunc: func(ctx context.Context, name string, command string, args []string, cwd string) error {
//				panic("mock out the RunSession method")
//			},
//			SessionExistsFunc: func(ctx context.Context, name string) (bool, error) {
//				panic("mock out the SessionExists method")
//			},
//		}
//
//		// use mockedClient in code that requires Client
//		// and then make assertions.
//
//	}
type ClientMock struct {
	// AttachSessionFunc mocks the AttachSession method.
	AttachSessionFunc func(ctx context.Context, name string, terminalCmdTemplate string) error

	// KillSessionFunc mocks the KillSession method.
	KillSessionFunc func(ctx context.Context, name string) error

	// ListSessionsFunc mocks the ListSessions method.
	ListSessionsFunc func(ctx context.Context, prefix string) ([]string, error)

	// RunSessionFunc mocks the RunSession method.
	RunSessionFunc func(ctx context.Context, name string, command string, args []string, cwd string) error

	// SessionExistsFunc mocks the SessionExists method.
	SessionExistsFunc func(ctx context.Context, name string) (bool, error)

	// calls tracks calls to the methods.
	calls struct {
		// AttachSession holds details about calls to the AttachSession method.
		AttachSession []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Name is the name argument value.
			Name string
			// TerminalCmdTemplate is the terminalCmdTemplate argument value.
			TerminalCmdTemplate string
		}
		// KillSession holds details about calls to the KillSession method.
		KillSession []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Name is the name argument value.
			Name string
		}
		// ListSessions holds details about calls to the ListSessions method.
		ListSessions []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Prefix is the prefix argument value.
			Prefix string
		}
		// RunSession holds details about calls to the RunSession method.
		RunSession []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Name is the name argument value.
			Name string
			// Command is the command argument value.
			Command string
			// Args is the args argument value.
			Args []string
			// Cwd is the cwd argument value.
			Cwd string
		}
		// SessionExists holds details about calls to the SessionExists method.
		SessionExists []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Name is the name argument value.
			Name string
		}
	}
	lockAttachSession sync.RWMutex
	lockKillSession   sync.RWMutex
	lockListSessions  sync.RWMutex
	lockRunSession    sync.RWMutex
	lockSessionExists sync.RWMutex
}

// AttachSession calls AttachSessionFunc.
func (mock *ClientMock) AttachSession(ctx context.Context, name string, terminalCmdTemplate string) error {
	callInfo := struct {
		Ctx                 context.Context
		Name                string
		TerminalCmdTemplate string
	}{
		Ctx:                 ctx,
		Name:                name,
		TerminalCmdTemplate: terminalCmdTemplate,
	}
	mock.lockAttachSession.Lock()
	mock.calls.AttachSession = append(mock.calls.AttachSession, callInfo)
	mock.lockAttachSession.Unlock()
	if mock.AttachSessionFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.AttachSessionFunc(ctx, name, terminalCmdTemplate)
}

// AttachSessionCalls gets all the calls that were made to AttachSession.
// Check the length with:
//
//	len(mockedClient.AttachSessionCalls())
func (mock *ClientMock) AttachSessionCalls() []struct {
	Ctx                 context.Context
	Name                string
	TerminalCmdTemplate string
} {
	var calls []struct {
		Ctx                 context.Context
		Name                string
		TerminalCmdTemplate string
	}
	mock.lockAttachSession.RLock()
	calls = mock.calls.AttachSession
	mock.lockAttachSession.RUnlock()
	return calls
}

// KillSession calls KillSessionFunc.
func (mock *ClientMock) KillSession(ctx context.Context, name string) error {
	callInfo := struct {
		Ctx  context.Context
		Name string
	}{
		Ctx:  ctx,
		Name: name,
	}
	mock.lockKillSession.Lock()
	mock.calls.KillSession = append(mock.calls.KillSession, callInfo)
	mock.lockKillSession.Unlock()
	if mock.KillSessionFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.KillSessionFunc(ctx, name)
}

// KillSessionCalls gets all the calls that were made to KillSession.
// Check the length with:
//
//	len(mockedClient.KillSessionCalls())
func (mock *ClientMock) KillSessionCalls() []struct {
	Ctx  context.Context
	Name string
} {
	var calls []struct {
		Ctx  context.Context
		Name string
	}
	mock.lockKillSession.RLock()
	calls = mock.calls.KillSession
	mock.lockKillSession.RUnlock()
	return calls
}

// ListSessions calls ListSessionsFunc.
func (mock *ClientMock) ListSessions(ctx context.Context, prefix string) ([]string, error) {
	callInfo := struct {
		Ctx    context.Context
		Prefix string
	}{
		Ctx:    ctx,
		Prefix: prefix,
	}
	mock.lockListSessions.Lock()
	mock.calls.ListSessions = append(mock.calls.ListSessions, callInfo)
	mock.lockListSessions.Unlock()
	if mock.ListSessionsFunc == nil {
		var (
			stringsOut []string
			errOut     error
		)
		return stringsOut, errOut
	}
	return mock.ListSessionsFunc(ctx, prefix)
}

// ListSessionsCalls gets all the calls that were made to ListSessions.
// Check the length with:
//
//	len(mockedClient.ListSessionsCalls())
func (mock *ClientMock) ListSessionsCalls() []struct {
	Ctx    context.Context
	Prefix string
} {
	var calls []struct {
		Ctx    context.Context
		Prefix string
	}
	mock.lockListSessions.RLock()
	calls = mock.calls.ListSessions
	mock.lockListSessions.RUnlock()
	return calls
}

// RunSession calls RunSessionFunc.
func (mock *ClientMock) RunSession(ctx context.Context, name string, command string, args []string, cwd string) error {
	callInfo := struct {
		Ctx     context.Context
		Name    string
		Command string
		Args    []string
		Cwd     string
	}{
		Ctx:     ctx,
		Name:    name,
		Command: command,
		Args:    args,
		Cwd:     cwd,
	}
	mock.lockRunSession.Lock()
	mock.calls.RunSession = append(mock.calls.RunSession, callInfo)
	mock.lockRunSession.Unlock()
	if mock.RunSessionFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.RunSessionFunc(ctx, name, command, args, cwd)
}

// RunSessionCalls gets all the calls that were made to RunSession.
// Check the length with:
//
//	len(mockedClient.RunSessionCalls())
func (mock *ClientMock) RunSessionCalls() []struct {
	Ctx     context.Context
	Name    string
	Command string
	Args    []string
	Cwd     string
} {
	var calls []struct {
		Ctx     context.Context
		Name    string
		Command string
		Args    []string
		Cwd     string
	}
	mock.lockRunSession.RLock()
	calls = mock.calls.RunSession
	mock.lockRunSession.RUnlock()
	return calls
}

// SessionExists calls SessionExistsFunc.
func (mock *ClientMock) SessionExists(ctx context.Context, name string) (bool, error) {
	callInfo := struct {
		Ctx  context.Context
		Name string
	}{
		Ctx:  ctx,
		Name: name,
	}
	mock.lockSessionExists.Lock()
	mock.calls.SessionExists = append(mock.calls.SessionExists, callInfo)
	mock.lockSessionExists.Unlock()
	if mock.SessionExistsFunc == nil {
		var (
			bOut   bool
			errOut error
		)
		return bOut, errOut
	}
	return mock.SessionExistsFunc(ctx, name)
}

// SessionExistsCalls gets all the calls that were made to SessionExists.
// Check the length with:
//
//	len(mockedClient.SessionExistsCalls())
func (mock *ClientMock) SessionExistsCalls() []struct {
	Ctx  context.Context
	Name string
} {
	var calls []struct {
		Ctx  context.Context
		Name string
	}
	mock.lockSessionExists.RLock()
	calls = mock.calls.SessionExists
	mock.lockSessionExists.RUnlock()
	return calls
}
