// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package task

import (
	"context"
	"github.com/sargehq/sarge/internal/beans"
	"sync"
)

// Ensure, that ComplexityEstimatorMock does implement ComplexityEstimator.
// If this is not the case, regenerate this file with moq.
var _ ComplexityEstimator = &ComplexityEstimatorMock{}

// ComplexityEstimatorMock is a mock implementation of ComplexityEstimator.
//
//	func TestSomethingThatUsesComplexityEstimator(t *testing.T) {
//
//		// make and configure a mocked ComplexityEstimator
//		mockedComplexityEstimator := &ComplexityEstimatorMock{
//			EstimateFunc: func(ctx context.Context, bead beans.Bean) (int, int, error) {
//				panic("mock out the Estimate method")
//			},
//		}
//
//		// use mockedComplexityEstimator in code that requires ComplexityEstimator
//		// and then make assertions.
//
//	}
type ComplexityEstimatorMock struct {
	// EstimateFunc mocks the Estimate method.
	EstimateFunc func(ctx context.Context, bead beans.Bean) (int, int, error)

	// calls tracks calls to the methods.
	calls struct {
		// Estimate holds details about calls to the Estimate method.
		Estimate []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Bead is the bead argument value.
			Bead beans.Bean
		}
	}
	lockEstimate sync.RWMutex
}

// Estimate calls EstimateFunc.
func (mock *ComplexityEstimatorMock) Estimate(ctx context.Context, bead beans.Bean) (int, int, error) {
	callInfo := struct {
		Ctx  context.Context
		Bead beans.Bean
	}{
		Ctx:  ctx,
		Bead: bead,
	}
	mock.lockEstimate.Lock()
	mock.calls.Estimate = append(mock.calls.Estimate, callInfo)
	mock.lockEstimate.Unlock()
	if mock.EstimateFunc == nil {
		var (
			scoreOut  int
			tokensOut int
			errOut    error
		)
		return scoreOut, tokensOut, errOut
	}
	return mock.EstimateFunc(ctx, bead)
}

// EstimateCalls gets all the calls that were made to Estimate.
// Check the length with:
//
//	len(mockedComplexityEstimator.EstimateCalls())
func (mock *ComplexityEstimatorMock) EstimateCalls() []struct {
	Ctx  context.Context
	Bead beans.Bean
} {
	var calls []struct {
		Ctx  context.Context
		Bead beans.Bean
	}
	mock.lockEstimate.RLock()
	calls = mock.calls.Estimate
	mock.lockEstimate.RUnlock()
	return calls
}

// Ensure, that PlannerMock does implement Planner.
// If this is not the case, regenerate this file with moq.
var _ Planner = &PlannerMock{}

// PlannerMock is a mock implementation of Planner.
//
//	func TestSomethingThatUsesPlanner(t *testing.T) {
//
//		// make and configure a mocked Planner
//		mockedPlanner := &PlannerMock{
//			PlanFunc: func(ctx context.Context, beadList []beans.Bean, dependencies map[string][]beans.Dependency, budget int) ([]Task, error) {
//				panic("mock out the Plan method")
//			},
//		}
//
//		// use mockedPlanner in code that requires Planner
//		// and then make assertions.
//
//	}
type PlannerMock struct {
	// PlanFunc mocks the Plan method.
	PlanFunc func(ctx context.Context, beadList []beans.Bean, dependencies map[string][]beans.Dependency, budget int) ([]Task, error)

	// calls tracks calls to the methods.
	calls struct {
		// Plan holds details about calls to the Plan method.
		Plan []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// BeadList is the beadList argument value.
			BeadList []beans.Bean
			// Dependencies is the dependencies argument value.
			Dependencies map[string][]beans.Dependency
			// Budget is the budget argument value.
			Budget int
		}
	}
	lockPlan sync.RWMutex
}

// Plan calls PlanFunc.
func (mock *PlannerMock) Plan(ctx context.Context, beadList []beans.Bean, dependencies map[string][]beans.Dependency, budget int) ([]Task, error) {
	callInfo := struct {
		Ctx          context.Context
		BeadList     []beans.Bean
		Dependencies map[string][]beans.Dependency
		Budget       int
	}{
		Ctx:          ctx,
		BeadList:     beadList,
		Dependencies: dependencies,
		Budget:       budget,
	}
	mock.lockPlan.Lock()
	mock.calls.Plan = append(mock.calls.Plan, callInfo)
	mock.lockPlan.Unlock()
	if mock.PlanFunc == nil {
		var (
			tasksOut []Task
			errOut   error
		)
		return tasksOut, errOut
	}
	return mock.PlanFunc(ctx, beadList, dependencies, budget)
}

// PlanCalls gets all the calls that were made to Plan.
// Check the length with:
//
//	len(mockedPlanner.PlanCalls())
func (mock *PlannerMock) PlanCalls() []struct {
	Ctx          context.Context
	BeadList     []beans.Bean
	Dependencies map[string][]beans.Dependency
	Budget       int
} {
	var calls []struct {
		Ctx          context.Context
		BeadList     []beans.Bean
		Dependencies map[string][]beans.Dependency
		Budget       int
	}
	mock.lockPlan.RLock()
	calls = mock.calls.Plan
	mock.lockPlan.RUnlock()
	return calls
}
