// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package feedback

import (
	"context"
	"github.com/sargehq/sarge/internal/db"
	"github.com/sargehq/sarge/internal/project"
	"sync"
)

// Ensure, that FeedbackProcessorMock does implement Processor.
// If this is not the case, regenerate this file with moq.
var _ Processor = &FeedbackProcessorMock{}

// FeedbackProcessorMock is a mock implementation of Processor.
//
//	func TestSomethingThatUsesProcessor(t *testing.T) {
//
//		// make and configure a mocked Processor
//		mockedProcessor := &FeedbackProcessorMock{
//			ProcessPRFeedbackFunc: func(ctx context.Context, proj *project.Project, database *db.DB, workID string) (int, error) {
//				panic("mock out the ProcessPRFeedback method")
//			},
//		}
//
//		// use mockedProcessor in code that requires Processor
//		// and then make assertions.
//
//	}
type FeedbackProcessorMock struct {
	// ProcessPRFeedbackFunc mocks the ProcessPRFeedback method.
	ProcessPRFeedbackFunc func(ctx context.Context, proj *project.Project, database *db.DB, workID string) (int, error)

	// calls tracks calls to the methods.
	calls struct {
		// ProcessPRFeedback holds details about calls to the ProcessPRFeedback method.
		ProcessPRFeedback []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Proj is the proj argument value.
			Proj *project.Project
			// Database is the database argument value.
			Database *db.DB
			// WorkID is the workID argument value.
			WorkID string
		}
	}
	lockProcessPRFeedback sync.RWMutex
}

// ProcessPRFeedback calls ProcessPRFeedbackFunc.
func (mock *FeedbackProcessorMock) ProcessPRFeedback(ctx context.Context, proj *project.Project, database *db.DB, workID string) (int, error) {
	callInfo := struct {
		Ctx      context.Context
		Proj     *project.Project
		Database *db.DB
		WorkID   string
	}{
		Ctx:      ctx,
		Proj:     proj,
		Database: database,
		WorkID:   workID,
	}
	mock.lockProcessPRFeedback.Lock()
	mock.calls.ProcessPRFeedback = append(mock.calls.ProcessPRFeedback, callInfo)
	mock.lockProcessPRFeedback.Unlock()
	if mock.ProcessPRFeedbackFunc == nil {
		var (
			nOut   int
			errOut error
		)
		return nOut, errOut
	}
	return mock.ProcessPRFeedbackFunc(ctx, proj, database, workID)
}

// ProcessPRFeedbackCalls gets all the calls that were made to ProcessPRFeedback.
// Check the length with:
//
//	len(mockedProcessor.ProcessPRFeedbackCalls())
func (mock *FeedbackProcessorMock) ProcessPRFeedbackCalls() []struct {
	Ctx      context.Context
	Proj     *project.Project
	Database *db.DB
	WorkID   string
} {
	var calls []struct {
		Ctx      context.Context
		Proj     *project.Project
		Database *db.DB
		WorkID   string
	}
	mock.lockProcessPRFeedback.RLock()
	calls = mock.calls.ProcessPRFeedback
	mock.lockProcessPRFeedback.RUnlock()
	return calls
}
