// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package queries

import (
	"database/sql"
	"time"
)

type Dependency struct {
	IssueID     string         `json:"issue_id"`
	DependsOnID string         `json:"depends_on_id"`
	Type        string         `json:"type"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	CreatedBy   string         `json:"created_by"`
	Metadata    sql.NullString `json:"metadata"`
	ThreadID    sql.NullString `json:"thread_id"`
}

type Issue struct {
	ID                 string          `json:"id"`
	ContentHash        sql.NullString  `json:"content_hash"`
	Title              string          `json:"title"`
	Description        string          `json:"description"`
	Design             string          `json:"design"`
	AcceptanceCriteria string          `json:"acceptance_criteria"`
	Notes              string          `json:"notes"`
	Status             string          `json:"status"`
	Priority           int64           `json:"priority"`
	IssueType          string          `json:"issue_type"`
	Assignee           sql.NullString  `json:"assignee"`
	EstimatedMinutes   sql.NullInt64   `json:"estimated_minutes"`
	CreatedAt          time.Time       `json:"created_at"`
	CreatedBy          sql.NullString  `json:"created_by"`
	Owner              sql.NullString  `json:"owner"`
	UpdatedAt          time.Time       `json:"updated_at"`
	ClosedAt           sql.NullTime    `json:"closed_at"`
	ClosedBySession    sql.NullString  `json:"closed_by_session"`
	ExternalRef        sql.NullString  `json:"external_ref"`
	CompactionLevel    sql.NullInt64   `json:"compaction_level"`
	CompactedAt        sql.NullTime    `json:"compacted_at"`
	CompactedAtCommit  sql.NullString  `json:"compacted_at_commit"`
	OriginalSize       sql.NullInt64   `json:"original_size"`
	DeletedAt          sql.NullTime    `json:"deleted_at"`
	DeletedBy          sql.NullString  `json:"deleted_by"`
	DeleteReason       sql.NullString  `json:"delete_reason"`
	OriginalType       sql.NullString  `json:"original_type"`
	Sender             sql.NullString  `json:"sender"`
	Ephemeral          sql.NullInt64   `json:"ephemeral"`
	Pinned             sql.NullInt64   `json:"pinned"`
	IsTemplate         sql.NullInt64   `json:"is_template"`
	Crystallizes       sql.NullInt64   `json:"crystallizes"`
	MolType            sql.NullString  `json:"mol_type"`
	WorkType           sql.NullString  `json:"work_type"`
	QualityScore       sql.NullFloat64 `json:"quality_score"`
	SourceSystem       sql.NullString  `json:"source_system"`
	EventKind          sql.NullString  `json:"event_kind"`
	Actor              sql.NullString  `json:"actor"`
	Target             sql.NullString  `json:"target"`
	Payload            sql.NullString  `json:"payload"`
	SourceRepo         sql.NullString  `json:"source_repo"`
	CloseReason        sql.NullString  `json:"close_reason"`
	AwaitType          sql.NullString  `json:"await_type"`
	AwaitID            sql.NullString  `json:"await_id"`
	TimeoutNs          sql.NullInt64   `json:"timeout_ns"`
	Waiters            sql.NullString  `json:"waiters"`
	HookBead           sql.NullString  `json:"hook_bead"`
	RoleBead           sql.NullString  `json:"role_bead"`
	AgentState         sql.NullString  `json:"agent_state"`
	LastActivity       sql.NullTime    `json:"last_activity"`
	RoleType           sql.NullString  `json:"role_type"`
	Rig                sql.NullString  `json:"rig"`
	DueAt              sql.NullTime    `json:"due_at"`
	DeferUntil         sql.NullTime    `json:"defer_until"`
}
